#define	USBD_EP0_INT_EN_SETUP_Pos                           (0)
#define	USBD_EP0_INT_EN_SETUP                               (0x00U << USBD_EP0_INT_EN_SETUP_Pos)
#define	USBD_EP0_INT_EN_END_Pos                             (1)
#define	USBD_EP0_INT_EN_END                                 (0x01U << USBD_EP0_INT_EN_END_Pos)
#define	USBD_EP0_INT_EN_INNACK_Pos                          (2)
#define	USBD_EP0_INT_EN_INNACK                              (0x02U << USBD_EP0_INT_EN_INNACK_Pos)
#define	USBD_EP0_INT_EN_INACK_Pos                           (3)
#define	USBD_EP0_INT_EN_INACK                               (0x03U << USBD_EP0_INT_EN_INACK_Pos)
#define	USBD_EP0_INT_EN_INSTALL_Pos                         (4)
#define	USBD_EP0_INT_EN_INSTALL                             (0x04U << USBD_EP0_INT_EN_INSTALL_Pos)
#define	USBD_EP0_INT_EN_OUTNACK_Pos                         (5)
#define	USBD_EP0_INT_EN_OUTNACK                             (0x05U << USBD_EP0_INT_EN_OUTNACK_Pos)
#define	USBD_EP0_INT_EN_OUTACK_Pos                          (6)
#define	USBD_EP0_INT_EN_OUTACK                              (0x06U << USBD_EP0_INT_EN_OUTACK_Pos)
#define	USBD_EP0_INT_EN_OUTSTALL_Pos                        (7)
#define	USBD_EP0_INT_EN_OUTSTALL                            (0x07U << USBD_EP0_INT_EN_OUTSTALL_Pos)
