#define	USBD_EP_EN_EP0EN_Pos                                (0)
#define	USBD_EP_EN_EP0EN                                    (0x00U << USBD_EP_EN_EP0EN_Pos)
#define	USBD_EP_EN_EP1EN_Pos                                (1)
#define	USBD_EP_EN_EP1EN                                    (0x01U << USBD_EP_EN_EP1EN_Pos)
#define	USBD_EP_EN_EP2EN_Pos                                (2)
#define	USBD_EP_EN_EP2EN                                    (0x02U << USBD_EP_EN_EP2EN_Pos)
#define	USBD_EP_EN_EP3EN_Pos                                (3)
#define	USBD_EP_EN_EP3EN                                    (0x03U << USBD_EP_EN_EP3EN_Pos)
#define	USBD_EP_EN_EP4EN_Pos                                (4)
#define	USBD_EP_EN_EP4EN                                    (0x04U << USBD_EP_EN_EP4EN_Pos)
