#define	USBD_EP_HALT_HALT0_Pos                              (0)
#define	USBD_EP_HALT_HALT0                                  (0x00U << USBD_EP_HALT_HALT0_Pos)
#define	USBD_EP_HALT_HALT1_Pos                              (1)
#define	USBD_EP_HALT_HALT1                                  (0x01U << USBD_EP_HALT_HALT1_Pos)
#define	USBD_EP_HALT_HALT2_Pos                              (2)
#define	USBD_EP_HALT_HALT2                                  (0x02U << USBD_EP_HALT_HALT2_Pos)
#define	USBD_EP_HALT_HALT3_Pos                              (3)
#define	USBD_EP_HALT_HALT3                                  (0x03U << USBD_EP_HALT_HALT3_Pos)
#define	USBD_EP_HALT_HALT4_Pos                              (4)
#define	USBD_EP_HALT_HALT4                                  (0x04U << USBD_EP_HALT_HALT4_Pos)
