#define	USBD_EP_INT_STATE_EP0F_Pos                          (0)
#define	USBD_EP_INT_STATE_EP0F                              (0x00U << USBD_EP_INT_STATE_EP0F_Pos)
#define	USBD_EP_INT_STATE_EP1F_Pos                          (1)
#define	USBD_EP_INT_STATE_EP1F                              (0x01U << USBD_EP_INT_STATE_EP1F_Pos)
#define	USBD_EP_INT_STATE_EP2F_Pos                          (2)
#define	USBD_EP_INT_STATE_EP2F                              (0x02U << USBD_EP_INT_STATE_EP2F_Pos)
#define	USBD_EP_INT_STATE_EP3F_Pos                          (3)
#define	USBD_EP_INT_STATE_EP3F                              (0x03U << USBD_EP_INT_STATE_EP3F_Pos)
#define	USBD_EP_INT_STATE_EP4F_Pos                          (4)
#define	USBD_EP_INT_STATE_EP4F                              (0x04U << USBD_EP_INT_STATE_EP4F_Pos)
