#define	USBD_EP_INT_EN_EP0IE_Pos                            (0)
#define	USBD_EP_INT_EN_EP0IE                                (0x00U << USBD_EP_INT_EN_EP0IE_Pos)
#define	USBD_EP_INT_EN_EP1IE_Pos                            (1)
#define	USBD_EP_INT_EN_EP1IE                                (0x01U << USBD_EP_INT_EN_EP1IE_Pos)
#define	USBD_EP_INT_EN_EP2IE_Pos                            (2)
#define	USBD_EP_INT_EN_EP2IE                                (0x02U << USBD_EP_INT_EN_EP2IE_Pos)
#define	USBD_EP_INT_EN_EP3IE_Pos                            (3)
#define	USBD_EP_INT_EN_EP3IE                                (0x03U << USBD_EP_INT_EN_EP3IE_Pos)
#define	USBD_EP_INT_EN_EP4IE_Pos                            (4)
#define	USBD_EP_INT_EN_EP4IE                                (0x04U << USBD_EP_INT_EN_EP4IE_Pos)
