#define	USBD_EPn_INT_STATE_END_Pos                          (1)
#define	USBD_EPn_INT_STATE_END                              (0x01U << USBD_EPn_INT_STATE_END_Pos)
#define	USBD_EPn_INT_STATE_INNACK_Pos                       (2)
#define	USBD_EPn_INT_STATE_INNACK                           (0x02U << USBD_EPn_INT_STATE_INNACK_Pos)
#define	USBD_EPn_INT_STATE_INACK_Pos                        (3)
#define	USBD_EPn_INT_STATE_INACK                            (0x03U << USBD_EPn_INT_STATE_INACK_Pos)
#define	USBD_EPn_INT_STATE_INSTALL_Pos                      (4)
#define	USBD_EPn_INT_STATE_INSTALL                          (0x04U << USBD_EPn_INT_STATE_INSTALL_Pos)
#define	USBD_EPn_INT_STATE_OUTNACK_Pos                      (5)
#define	USBD_EPn_INT_STATE_OUTNACK                          (0x05U << USBD_EPn_INT_STATE_OUTNACK_Pos)
#define	USBD_EPn_INT_STATE_OUTACK_Pos                       (6)
#define	USBD_EPn_INT_STATE_OUTACK                           (0x06U << USBD_EPn_INT_STATE_OUTACK_Pos)
#define	USBD_EPn_INT_STATE_OUTSTALL_Pos                     (7)
#define	USBD_EPn_INT_STATE_OUTSTALL                         (0x07U << USBD_EPn_INT_STATE_OUTSTALL_Pos)
