#define	USBD_EPn_INT_EN_SETUPIE_Pos                         (0)
#define	USBD_EPn_INT_EN_SETUPIE                             (0x00U << USBD_EPn_INT_EN_SETUPIE_Pos)
#define	USBD_EPn_INT_EN_ENDIE_Pos                           (1)
#define	USBD_EPn_INT_EN_ENDIE                               (0x01U << USBD_EPn_INT_EN_ENDIE_Pos)
#define	USBD_EPn_INT_EN_INNACKIE_Pos                        (2)
#define	USBD_EPn_INT_EN_INNACKIE                            (0x02U << USBD_EPn_INT_EN_INNACKIE_Pos)
#define	USBD_EPn_INT_EN_INACKIE_Pos                         (3)
#define	USBD_EPn_INT_EN_INACKIE                             (0x03U << USBD_EPn_INT_EN_INACKIE_Pos)
#define	USBD_EPn_INT_EN_INSTALLIE_Pos                       (4)
#define	USBD_EPn_INT_EN_INSTALLIE                           (0x04U << USBD_EPn_INT_EN_INSTALLIE_Pos)
#define	USBD_EPn_INT_EN_OUTNACKIE_Pos                       (5)
#define	USBD_EPn_INT_EN_OUTNACKIE                           (0x05U << USBD_EPn_INT_EN_OUTNACKIE_Pos)
#define	USBD_EPn_INT_EN_OUTACKIE_Pos                        (6)
#define	USBD_EPn_INT_EN_OUTACKIE                            (0x06U << USBD_EPn_INT_EN_OUTACKIE_Pos)
#define	USBD_EPn_INT_EN_OUTSTALLIE_Pos                      (7)
#define	USBD_EPn_INT_EN_OUTSTALLIE                          (0x07U << USBD_EPn_INT_EN_OUTSTALLIE_Pos)
