#define	USBD_TOG_CTRL1_4_DTOG1_Pos                          (0)
#define	USBD_TOG_CTRL1_4_DTOG1                              (0x00U << USBD_TOG_CTRL1_4_DTOG1_Pos)
#define	USBD_TOG_CTRL1_4_DTOG1EN_Pos                        (1)
#define	USBD_TOG_CTRL1_4_DTOG1EN                            (0x01U << USBD_TOG_CTRL1_4_DTOG1EN_Pos)
#define	USBD_TOG_CTRL1_4_DTOG2_Pos                          (2)
#define	USBD_TOG_CTRL1_4_DTOG2                              (0x02U << USBD_TOG_CTRL1_4_DTOG2_Pos)
#define	USBD_TOG_CTRL1_4_DTOG2EN_Pos                        (3)
#define	USBD_TOG_CTRL1_4_DTOG2EN                            (0x03U << USBD_TOG_CTRL1_4_DTOG2EN_Pos)
#define	USBD_TOG_CTRL1_4_DTOG3_Pos                          (4)
#define	USBD_TOG_CTRL1_4_DTOG3                              (0x04U << USBD_TOG_CTRL1_4_DTOG3_Pos)
#define	USBD_TOG_CTRL1_4_DTOG3EN_Pos                        (5)
#define	USBD_TOG_CTRL1_4_DTOG3EN                            (0x05U << USBD_TOG_CTRL1_4_DTOG3EN_Pos)
#define	USBD_TOG_CTRL1_4_DTOG4_Pos                          (6)
#define	USBD_TOG_CTRL1_4_DTOG4                              (0x06U << USBD_TOG_CTRL1_4_DTOG4_Pos)
#define	USBD_TOG_CTRL1_4_DTOG4EN_Pos                        (7)
#define	USBD_TOG_CTRL1_4_DTOG4EN                            (0x07U << USBD_TOG_CTRL1_4_DTOG4EN_Pos)
