#define	USBD_USB_INT_EN_RSTIE_Pos                           (0)
#define	USBD_USB_INT_EN_RSTIE                               (0x00U << USBD_USB_INT_EN_RSTIE_Pos)
#define	USBD_USB_INT_EN_SUSPENDIE_Pos                       (1)
#define	USBD_USB_INT_EN_SUSPENDIE                           (0x01U << USBD_USB_INT_EN_SUSPENDIE_Pos)
#define	USBD_USB_INT_EN_RESUMIE_Pos                         (2)
#define	USBD_USB_INT_EN_RESUMIE                             (0x02U << USBD_USB_INT_EN_RESUMIE_Pos)
#define	USBD_USB_INT_EN_SOFIE_Pos                           (3)
#define	USBD_USB_INT_EN_SOFIE                               (0x03U << USBD_USB_INT_EN_SOFIE_Pos)
#define	USBD_USB_INT_EN_EPIE_Pos                            (4)
#define	USBD_USB_INT_EN_EPIE                                (0x04U << USBD_USB_INT_EN_EPIE_Pos)
#define	USBD_USB_INT_EN_INTMASK_Pos                         (7)
#define	USBD_USB_INT_EN_INTMASK                             (0x06U << USBD_USB_INT_EN_INTMASK_Pos)
