#define	USBD_USB_INT_STATE_RSTF_Pos                         (0)
#define	USBD_USB_INT_STATE_RSTF                             (0x00U << USBD_USB_INT_STATE_RSTF_Pos)
#define	USBD_USB_INT_STATE_SUSPENDF_Pos                     (1)
#define	USBD_USB_INT_STATE_SUSPENDF                         (0x01U << USBD_USB_INT_STATE_SUSPENDF_Pos)
#define	USBD_USB_INT_STATE_RESUMF_Pos                       (2)
#define	USBD_USB_INT_STATE_RESUMF                           (0x02U << USBD_USB_INT_STATE_RESUMF_Pos)
#define	USBD_USB_INT_STATE_SOFF_Pos                         (3)
#define	USBD_USB_INT_STATE_SOFF                             (0x03U << USBD_USB_INT_STATE_SOFF_Pos)
#define	USBD_USB_INT_STATE_EPINTF_Pos                       (4)
#define	USBD_USB_INT_STATE_EPINTF                           (0x04U << USBD_USB_INT_STATE_EPINTF_Pos)
