#define	USBD_USB_TOP_SPEED_Pos                              (0)
#define	USBD_USB_TOP_SPEED                                  (0x00U << USBD_USB_TOP_SPEED_Pos)
#define	USBD_USB_TOP_CONNECT_Pos                            (1)
#define	USBD_USB_TOP_CONNECT                                (0x01U << USBD_USB_TOP_CONNECT_Pos)
#define	USBD_USB_TOP_RESET_Pos                              (3)
#define	USBD_USB_TOP_RESET                                  (0x03U << USBD_USB_TOP_RESET_Pos)
#define	USBD_USB_TOP_SUSPEND_Pos                            (4)
#define	USBD_USB_TOP_SUSPEND                                (0x04U << USBD_USB_TOP_SUSPEND_Pos)
#define	USBD_USB_TOP_STATE_Pos                              (6)
#define	USBD_USB_TOP_STATE                                  (0x05U << USBD_USB_TOP_STATE_Pos)
#define	USBD_USB_TOP_ACTIVE_Pos                             (7)
#define	USBD_USB_TOP_ACTIVE                                 (0x06U << USBD_USB_TOP_ACTIVE_Pos)
