#define	SPI_CCR_CPHA_Pos                                    (0)
#define	SPI_CCR_CPHA                                        (0x00U << SPI_CCR_CPHA_Pos)
#define	SPI_CCR_CPOL_Pos                                    (1)
#define	SPI_CCR_CPOL                                        (0x01U << SPI_CCR_CPOL_Pos)
#define	SPI_CCR_LSBFE_Pos                                   (2)
#define	SPI_CCR_LSBFE                                       (0x02U << SPI_CCR_LSBFE_Pos)
#define	SPI_CCR_SPILEN_Pos                                  (3)
#define	SPI_CCR_SPILEN                                      (0x03U << SPI_CCR_SPILEN_Pos)
#define	SPI_CCR_RXEDGE_Pos                                  (4)
#define	SPI_CCR_RXEDGE                                      (0x04U << SPI_CCR_RXEDGE_Pos)
#define	SPI_CCR_TXEDGE_Pos                                  (5)
#define	SPI_CCR_TXEDGE                                      (0x05U << SPI_CCR_TXEDGE_Pos)
