#define	SPI_GCR_SPIEN_Pos                                   (0)
#define	SPI_GCR_SPIEN                                       (0x00U << SPI_GCR_SPIEN_Pos)
#define	SPI_GCR_IEN_Pos                                     (1)
#define	SPI_GCR_IEN                                         (0x01U << SPI_GCR_IEN_Pos)
#define	SPI_GCR_MODE_Pos                                    (2)
#define	SPI_GCR_MODE                                        (0x02U << SPI_GCR_MODE_Pos)
#define	SPI_GCR_TXEN_Pos                                    (3)
#define	SPI_GCR_TXEN                                        (0x03U << SPI_GCR_TXEN_Pos)
#define	SPI_GCR_RXEN_Pos                                    (4)
#define	SPI_GCR_RXEN                                        (0x04U << SPI_GCR_RXEN_Pos)
#define	SPI_GCR_RXTLF_Pos                                   (6)
#define	SPI_GCR_RXTLF                                       (0x05U << SPI_GCR_RXTLF_Pos)
#define	SPI_GCR_TXTLF_Pos                                   (8)
#define	SPI_GCR_TXTLF                                       (0x06U << SPI_GCR_TXTLF_Pos)
#define	SPI_GCR_DMAEN_Pos                                   (9)
#define	SPI_GCR_DMAEN                                       (0x07U << SPI_GCR_DMAEN_Pos)
#define	SPI_GCR_NSS_Pos                                     (10)
#define	SPI_GCR_NSS                                         (0x08U << SPI_GCR_NSS_Pos)
#define	SPI_GCR_DWSEL_Pos                                   (11)
#define	SPI_GCR_DWSEL                                       (0x09U << SPI_GCR_DWSEL_Pos)
