#define	SPI_ICR_TX_Pos                                      (0)
#define	SPI_ICR_TX                                          (0x00U << SPI_ICR_TX_Pos)
#define	SPI_ICR_RX_Pos                                      (1)
#define	SPI_ICR_RX                                          (0x01U << SPI_ICR_RX_Pos)
#define	SPI_ICR_UNDERRUN_Pos                                (2)
#define	SPI_ICR_UNDERRUN                                    (0x02U << SPI_ICR_UNDERRUN_Pos)
#define	SPI_ICR_RXOERR_Pos                                  (3)
#define	SPI_ICR_RXOERR                                      (0x03U << SPI_ICR_RXOERR_Pos)
#define	SPI_ICR_RXMATCH_Pos                                 (4)
#define	SPI_ICR_RXMATCH                                     (0x04U << SPI_ICR_RXMATCH_Pos)
#define	SPI_ICR_RXFULL_Pos                                  (5)
#define	SPI_ICR_RXFULL                                      (0x05U << SPI_ICR_RXFULL_Pos)
#define	SPI_ICR_TXEPT_Pos                                   (6)
#define	SPI_ICR_TXEPT                                       (0x06U << SPI_ICR_TXEPT_Pos)
