#define	SPI_ISR_TX_Pos                                      (0)
#define	SPI_ISR_TX                                          (0x00U << SPI_ISR_TX_Pos)
#define	SPI_ISR_RX_Pos                                      (1)
#define	SPI_ISR_RX                                          (0x01U << SPI_ISR_RX_Pos)
#define	SPI_ISR_UNDERRUN_Pos                                (2)
#define	SPI_ISR_UNDERRUN                                    (0x02U << SPI_ISR_UNDERRUN_Pos)
#define	SPI_ISR_RXOERR_Pos                                  (3)
#define	SPI_ISR_RXOERR                                      (0x03U << SPI_ISR_RXOERR_Pos)
#define	SPI_ISR_RXMATCH_Pos                                 (4)
#define	SPI_ISR_RXMATCH                                     (0x04U << SPI_ISR_RXMATCH_Pos)
#define	SPI_ISR_RXFULL_Pos                                  (5)
#define	SPI_ISR_RXFULL                                      (0x05U << SPI_ISR_RXFULL_Pos)
#define	SPI_ISR_TXEPT_Pos                                   (6)
#define	SPI_ISR_TXEPT                                       (0x06U << SPI_ISR_TXEPT_Pos)
