#define	SPI_SR_TXEPT_Pos                                    (0)
#define	SPI_SR_TXEPT                                        (0x00U << SPI_SR_TXEPT_Pos)
#define	SPI_SR_RXAVL_Pos                                    (1)
#define	SPI_SR_RXAVL                                        (0x01U << SPI_SR_RXAVL_Pos)
#define	SPI_SR_TXFULL_Pos                                   (2)
#define	SPI_SR_TXFULL                                       (0x02U << SPI_SR_TXFULL_Pos)
#define	SPI_SR_RXAVL_4BYTE_Pos                              (3)
#define	SPI_SR_RXAVL_4BYTE                                  (0x03U << SPI_SR_RXAVL_4BYTE_Pos)
#define	SPI_SR_TXFADDR_Pos                                  (7)
#define	SPI_SR_TXFADDR                                      (0x04U << SPI_SR_TXFADDR_Pos)
#define	SPI_SR_RXFADDR_Pos                                  (11)
#define	SPI_SR_RXFADDR                                      (0x05U << SPI_SR_RXFADDR_Pos)
