#define	GPIO_BSRR_BS0_Pos                                   (0)
#define	GPIO_BSRR_BS0                                       (0x00U << GPIO_BSRR_BS0_Pos)
#define	GPIO_BSRR_BS1_Pos                                   (1)
#define	GPIO_BSRR_BS1                                       (0x01U << GPIO_BSRR_BS1_Pos)
#define	GPIO_BSRR_BS2_Pos                                   (2)
#define	GPIO_BSRR_BS2                                       (0x02U << GPIO_BSRR_BS2_Pos)
#define	GPIO_BSRR_BS3_Pos                                   (3)
#define	GPIO_BSRR_BS3                                       (0x03U << GPIO_BSRR_BS3_Pos)
#define	GPIO_BSRR_BS4_Pos                                   (4)
#define	GPIO_BSRR_BS4                                       (0x04U << GPIO_BSRR_BS4_Pos)
#define	GPIO_BSRR_BS5_Pos                                   (5)
#define	GPIO_BSRR_BS5                                       (0x05U << GPIO_BSRR_BS5_Pos)
#define	GPIO_BSRR_BS6_Pos                                   (6)
#define	GPIO_BSRR_BS6                                       (0x06U << GPIO_BSRR_BS6_Pos)
#define	GPIO_BSRR_BS7_Pos                                   (7)
#define	GPIO_BSRR_BS7                                       (0x07U << GPIO_BSRR_BS7_Pos)
#define	GPIO_BSRR_BS8_Pos                                   (8)
#define	GPIO_BSRR_BS8                                       (0x08U << GPIO_BSRR_BS8_Pos)
#define	GPIO_BSRR_BS9_Pos                                   (9)
#define	GPIO_BSRR_BS9                                       (0x09U << GPIO_BSRR_BS9_Pos)
#define	GPIO_BSRR_BS10_Pos                                  (10)
#define	GPIO_BSRR_BS10                                      (0x0AU << GPIO_BSRR_BS10_Pos)
#define	GPIO_BSRR_BS11_Pos                                  (11)
#define	GPIO_BSRR_BS11                                      (0x0BU << GPIO_BSRR_BS11_Pos)
#define	GPIO_BSRR_BS12_Pos                                  (12)
#define	GPIO_BSRR_BS12                                      (0x0CU << GPIO_BSRR_BS12_Pos)
#define	GPIO_BSRR_BS13_Pos                                  (13)
#define	GPIO_BSRR_BS13                                      (0x0DU << GPIO_BSRR_BS13_Pos)
#define	GPIO_BSRR_BS14_Pos                                  (14)
#define	GPIO_BSRR_BS14                                      (0x0EU << GPIO_BSRR_BS14_Pos)
#define	GPIO_BSRR_BS15_Pos                                  (15)
#define	GPIO_BSRR_BS15                                      (0x0FU << GPIO_BSRR_BS15_Pos)
#define	GPIO_BSRR_BR0_Pos                                   (16)
#define	GPIO_BSRR_BR0                                       (0x010U << GPIO_BSRR_BR0_Pos)
#define	GPIO_BSRR_BR1_Pos                                   (17)
#define	GPIO_BSRR_BR1                                       (0x011U << GPIO_BSRR_BR1_Pos)
#define	GPIO_BSRR_BR2_Pos                                   (18)
#define	GPIO_BSRR_BR2                                       (0x012U << GPIO_BSRR_BR2_Pos)
#define	GPIO_BSRR_BR3_Pos                                   (19)
#define	GPIO_BSRR_BR3                                       (0x013U << GPIO_BSRR_BR3_Pos)
#define	GPIO_BSRR_BR4_Pos                                   (20)
#define	GPIO_BSRR_BR4                                       (0x014U << GPIO_BSRR_BR4_Pos)
#define	GPIO_BSRR_BR5_Pos                                   (21)
#define	GPIO_BSRR_BR5                                       (0x015U << GPIO_BSRR_BR5_Pos)
#define	GPIO_BSRR_BR6_Pos                                   (22)
#define	GPIO_BSRR_BR6                                       (0x016U << GPIO_BSRR_BR6_Pos)
#define	GPIO_BSRR_BR7_Pos                                   (23)
#define	GPIO_BSRR_BR7                                       (0x017U << GPIO_BSRR_BR7_Pos)
#define	GPIO_BSRR_BR8_Pos                                   (24)
#define	GPIO_BSRR_BR8                                       (0x018U << GPIO_BSRR_BR8_Pos)
#define	GPIO_BSRR_BR9_Pos                                   (25)
#define	GPIO_BSRR_BR9                                       (0x019U << GPIO_BSRR_BR9_Pos)
#define	GPIO_BSRR_BR10_Pos                                  (26)
#define	GPIO_BSRR_BR10                                      (0x01AU << GPIO_BSRR_BR10_Pos)
#define	GPIO_BSRR_BR11_Pos                                  (27)
#define	GPIO_BSRR_BR11                                      (0x01BU << GPIO_BSRR_BR11_Pos)
#define	GPIO_BSRR_BR12_Pos                                  (28)
#define	GPIO_BSRR_BR12                                      (0x01CU << GPIO_BSRR_BR12_Pos)
#define	GPIO_BSRR_BR13_Pos                                  (29)
#define	GPIO_BSRR_BR13                                      (0x01DU << GPIO_BSRR_BR13_Pos)
#define	GPIO_BSRR_BR14_Pos                                  (30)
#define	GPIO_BSRR_BR14                                      (0x01EU << GPIO_BSRR_BR14_Pos)
#define	GPIO_BSRR_BR15_Pos                                  (31)
#define	GPIO_BSRR_BR15                                      (0x01FU << GPIO_BSRR_BR15_Pos)
