#define	GPIO_CRH_MODE8_Pos                                  (1)
#define	GPIO_CRH_MODE8                                      (0x00U << GPIO_CRH_MODE8_Pos)
#define	GPIO_CRH_CNF8_Pos                                   (3)
#define	GPIO_CRH_CNF8                                       (0x01U << GPIO_CRH_CNF8_Pos)
#define	GPIO_CRH_MODE9_Pos                                  (5)
#define	GPIO_CRH_MODE9                                      (0x02U << GPIO_CRH_MODE9_Pos)
#define	GPIO_CRH_CNF9_Pos                                   (7)
#define	GPIO_CRH_CNF9                                       (0x03U << GPIO_CRH_CNF9_Pos)
#define	GPIO_CRH_MODE10_Pos                                 (9)
#define	GPIO_CRH_MODE10                                     (0x04U << GPIO_CRH_MODE10_Pos)
#define	GPIO_CRH_CNF10_Pos                                  (11)
#define	GPIO_CRH_CNF10                                      (0x05U << GPIO_CRH_CNF10_Pos)
#define	GPIO_CRH_MODE11_Pos                                 (13)
#define	GPIO_CRH_MODE11                                     (0x06U << GPIO_CRH_MODE11_Pos)
#define	GPIO_CRH_CNF11_Pos                                  (15)
#define	GPIO_CRH_CNF11                                      (0x07U << GPIO_CRH_CNF11_Pos)
#define	GPIO_CRH_MODE12_Pos                                 (17)
#define	GPIO_CRH_MODE12                                     (0x08U << GPIO_CRH_MODE12_Pos)
#define	GPIO_CRH_CNF12_Pos                                  (19)
#define	GPIO_CRH_CNF12                                      (0x09U << GPIO_CRH_CNF12_Pos)
#define	GPIO_CRH_MODE13_Pos                                 (21)
#define	GPIO_CRH_MODE13                                     (0x0AU << GPIO_CRH_MODE13_Pos)
#define	GPIO_CRH_CNF13_Pos                                  (23)
#define	GPIO_CRH_CNF13                                      (0x0BU << GPIO_CRH_CNF13_Pos)
#define	GPIO_CRH_MODE14_Pos                                 (25)
#define	GPIO_CRH_MODE14                                     (0x0CU << GPIO_CRH_MODE14_Pos)
#define	GPIO_CRH_CNF14_Pos                                  (27)
#define	GPIO_CRH_CNF14                                      (0x0DU << GPIO_CRH_CNF14_Pos)
#define	GPIO_CRH_MODE15_Pos                                 (29)
#define	GPIO_CRH_MODE15                                     (0x0EU << GPIO_CRH_MODE15_Pos)
#define	GPIO_CRH_CNF15_Pos                                  (31)
#define	GPIO_CRH_CNF15                                      (0x0FU << GPIO_CRH_CNF15_Pos)
