#define	GPIO_CRL_MODE0_Pos                                  (1)
#define	GPIO_CRL_MODE0                                      (0x00U << GPIO_CRL_MODE0_Pos)
#define	GPIO_CRL_CNF0_Pos                                   (3)
#define	GPIO_CRL_CNF0                                       (0x01U << GPIO_CRL_CNF0_Pos)
#define	GPIO_CRL_MODE1_Pos                                  (5)
#define	GPIO_CRL_MODE1                                      (0x02U << GPIO_CRL_MODE1_Pos)
#define	GPIO_CRL_CNF1_Pos                                   (7)
#define	GPIO_CRL_CNF1                                       (0x03U << GPIO_CRL_CNF1_Pos)
#define	GPIO_CRL_MODE2_Pos                                  (9)
#define	GPIO_CRL_MODE2                                      (0x04U << GPIO_CRL_MODE2_Pos)
#define	GPIO_CRL_CNF2_Pos                                   (11)
#define	GPIO_CRL_CNF2                                       (0x05U << GPIO_CRL_CNF2_Pos)
#define	GPIO_CRL_MODE3_Pos                                  (13)
#define	GPIO_CRL_MODE3                                      (0x06U << GPIO_CRL_MODE3_Pos)
#define	GPIO_CRL_CNF3_Pos                                   (15)
#define	GPIO_CRL_CNF3                                       (0x07U << GPIO_CRL_CNF3_Pos)
#define	GPIO_CRL_MODE4_Pos                                  (17)
#define	GPIO_CRL_MODE4                                      (0x08U << GPIO_CRL_MODE4_Pos)
#define	GPIO_CRL_CNF4_Pos                                   (19)
#define	GPIO_CRL_CNF4                                       (0x09U << GPIO_CRL_CNF4_Pos)
#define	GPIO_CRL_MODE5_Pos                                  (21)
#define	GPIO_CRL_MODE5                                      (0x0AU << GPIO_CRL_MODE5_Pos)
#define	GPIO_CRL_CNF5_Pos                                   (23)
#define	GPIO_CRL_CNF5                                       (0x0BU << GPIO_CRL_CNF5_Pos)
#define	GPIO_CRL_MODE6_Pos                                  (25)
#define	GPIO_CRL_MODE6                                      (0x0CU << GPIO_CRL_MODE6_Pos)
#define	GPIO_CRL_CNF6_Pos                                   (27)
#define	GPIO_CRL_CNF6                                       (0x0DU << GPIO_CRL_CNF6_Pos)
#define	GPIO_CRL_MODE7_Pos                                  (29)
#define	GPIO_CRL_MODE7                                      (0x0EU << GPIO_CRL_MODE7_Pos)
#define	GPIO_CRL_CNF7_Pos                                   (31)
#define	GPIO_CRL_CNF7                                       (0x0FU << GPIO_CRL_CNF7_Pos)
