#define	GPIO_MAPR_SPI1_REMAP_Pos                            (0)
#define	GPIO_MAPR_SPI1_REMAP                                (0x00U << GPIO_MAPR_SPI1_REMAP_Pos)
#define	GPIO_MAPR_I2C1_REMAP_Pos                            (1)
#define	GPIO_MAPR_I2C1_REMAP                                (0x01U << GPIO_MAPR_I2C1_REMAP_Pos)
#define	GPIO_MAPR_UART1_REMAP_Pos                           (2)
#define	GPIO_MAPR_UART1_REMAP                               (0x02U << GPIO_MAPR_UART1_REMAP_Pos)
#define	GPIO_MAPR_UART3_REMAP_Pos                           (5)
#define	GPIO_MAPR_UART3_REMAP                               (0x04U << GPIO_MAPR_UART3_REMAP_Pos)
#define	GPIO_MAPR_TIM1_REMAP_Pos                            (7)
#define	GPIO_MAPR_TIM1_REMAP                                (0x05U << GPIO_MAPR_TIM1_REMAP_Pos)
#define	GPIO_MAPR_TIM2_REMAP_Pos                            (9)
#define	GPIO_MAPR_TIM2_REMAP                                (0x06U << GPIO_MAPR_TIM2_REMAP_Pos)
#define	GPIO_MAPR_TIM3_REMAP_Pos                            (11)
#define	GPIO_MAPR_TIM3_REMAP                                (0x07U << GPIO_MAPR_TIM3_REMAP_Pos)
#define	GPIO_MAPR_CAN_REMAP_Pos                             (14)
#define	GPIO_MAPR_CAN_REMAP                                 (0x09U << GPIO_MAPR_CAN_REMAP_Pos)
#define	GPIO_MAPR_PD01_REMAP_Pos                            (15)
#define	GPIO_MAPR_PD01_REMAP                                (0x0AU << GPIO_MAPR_PD01_REMAP_Pos)
#define	GPIO_MAPR_SWJ_CFG_Pos                               (26)
#define	GPIO_MAPR_SWJ_CFG                                   (0x0CU << GPIO_MAPR_SWJ_CFG_Pos)
