#define	UART_CCR_PEN_Pos                                    (0)
#define	UART_CCR_PEN                                        (0x00U << UART_CCR_PEN_Pos)
#define	UART_CCR_PSEL_Pos                                   (1)
#define	UART_CCR_PSEL                                       (0x01U << UART_CCR_PSEL_Pos)
#define	UART_CCR_SPB_Pos                                    (2)
#define	UART_CCR_SPB                                        (0x02U << UART_CCR_SPB_Pos)
#define	UART_CCR_BRK_Pos                                    (3)
#define	UART_CCR_BRK                                        (0x03U << UART_CCR_BRK_Pos)
#define	UART_CCR_CHAR_Pos                                   (5)
#define	UART_CCR_CHAR                                       (0x04U << UART_CCR_CHAR_Pos)
