#define	UART_GCR_UARTEN_Pos                                 (0)
#define	UART_GCR_UARTEN                                     (0x00U << UART_GCR_UARTEN_Pos)
#define	UART_GCR_DMAMODE_Pos                                (1)
#define	UART_GCR_DMAMODE                                    (0x01U << UART_GCR_DMAMODE_Pos)
#define	UART_GCR_AUTOFLOWEN_Pos                             (2)
#define	UART_GCR_AUTOFLOWEN                                 (0x02U << UART_GCR_AUTOFLOWEN_Pos)
#define	UART_GCR_RXEN_Pos                                   (3)
#define	UART_GCR_RXEN                                       (0x03U << UART_GCR_RXEN_Pos)
#define	UART_GCR_TXEN_Pos                                   (4)
#define	UART_GCR_TXEN                                       (0x04U << UART_GCR_TXEN_Pos)
