#define	UART_ICR_TXICLR_Pos                                 (0)
#define	UART_ICR_TXICLR                                     (0x00U << UART_ICR_TXICLR_Pos)
#define	UART_ICR_RXICLR_Pos                                 (1)
#define	UART_ICR_RXICLR                                     (0x01U << UART_ICR_RXICLR_Pos)
#define	UART_ICR_RXOERRCLR_Pos                              (3)
#define	UART_ICR_RXOERRCLR                                  (0x03U << UART_ICR_RXOERRCLR_Pos)
#define	UART_ICR_RXPERRCLR_Pos                              (4)
#define	UART_ICR_RXPERRCLR                                  (0x04U << UART_ICR_RXPERRCLR_Pos)
#define	UART_ICR_RXFERRCLR_Pos                              (5)
#define	UART_ICR_RXFERRCLR                                  (0x05U << UART_ICR_RXFERRCLR_Pos)
#define	UART_ICR_RXBRKCLR_Pos                               (6)
#define	UART_ICR_RXBRKCLR                                   (0x06U << UART_ICR_RXBRKCLR_Pos)
