#define	UART_IER_TXIEN_Pos                                  (0)
#define	UART_IER_TXIEN                                      (0x00U << UART_IER_TXIEN_Pos)
#define	UART_IER_RXIEN_Pos                                  (1)
#define	UART_IER_RXIEN                                      (0x01U << UART_IER_RXIEN_Pos)
#define	UART_IER_RXOERREN_Pos                               (3)
#define	UART_IER_RXOERREN                                   (0x03U << UART_IER_RXOERREN_Pos)
#define	UART_IER_RXPERREN_Pos                               (4)
#define	UART_IER_RXPERREN                                   (0x04U << UART_IER_RXPERREN_Pos)
#define	UART_IER_RXFERREN_Pos                               (5)
#define	UART_IER_RXFERREN                                   (0x05U << UART_IER_RXFERREN_Pos)
#define	UART_IER_RXBRKEN_Pos                                (6)
#define	UART_IER_RXBRKEN                                    (0x06U << UART_IER_RXBRKEN_Pos)
