#define	UART_ISR_TX_INTF_Pos                                (0)
#define	UART_ISR_TX_INTF                                    (0x00U << UART_ISR_TX_INTF_Pos)
#define	UART_ISR_RX_INTF_Pos                                (1)
#define	UART_ISR_RX_INTF                                    (0x01U << UART_ISR_RX_INTF_Pos)
#define	UART_ISR_RXOERR_INTF_Pos                            (3)
#define	UART_ISR_RXOERR_INTF                                (0x03U << UART_ISR_RXOERR_INTF_Pos)
#define	UART_ISR_RXPERR_INTF_Pos                            (4)
#define	UART_ISR_RXPERR_INTF                                (0x04U << UART_ISR_RXPERR_INTF_Pos)
#define	UART_ISR_RXFERR_INTF_Pos                            (5)
#define	UART_ISR_RXFERR_INTF                                (0x05U << UART_ISR_RXFERR_INTF_Pos)
#define	UART_ISR_RXBRK_INTF_Pos                             (6)
#define	UART_ISR_RXBRK_INTF                                 (0x06U << UART_ISR_RXBRK_INTF_Pos)
