#define	SPI_ISR_TXE_Pos                                     (0)
#define	SPI_ISR_TXE                                         (0x00U << SPI_ISR_TXE_Pos)
#define	SPI_ISR_TXC_Pos                                     (1)
#define	SPI_ISR_TXC                                         (0x01U << SPI_ISR_TXC_Pos)
#define	SPI_ISR_RXNE_Pos                                    (2)
#define	SPI_ISR_RXNE                                        (0x02U << SPI_ISR_RXNE_Pos)
#define	SPI_ISR_OVER_Pos                                    (3)
#define	SPI_ISR_OVER                                        (0x03U << SPI_ISR_OVER_Pos)
#define	SPI_ISR_TUDR_Pos                                    (4)
#define	SPI_ISR_TUDR                                        (0x04U << SPI_ISR_TUDR_Pos)
#define	SPI_ISR_RMAH_Pos                                    (5)
#define	SPI_ISR_RMAH                                        (0x05U << SPI_ISR_RMAH_Pos)
#define	SPI_ISR_STXE_Pos                                    (6)
#define	SPI_ISR_STXE                                        (0x06U << SPI_ISR_STXE_Pos)
#define	SPI_ISR_SRXNE_Pos                                   (7)
#define	SPI_ISR_SRXNE                                       (0x07U << SPI_ISR_SRXNE_Pos)
