#define	EXTI_CR1_EXTI0_Pos                                  (3)
#define	EXTI_CR1_EXTI0                                      (0x00U << EXTI_CR1_EXTI0_Pos)
#define	EXTI_CR1_EXTI1_Pos                                  (7)
#define	EXTI_CR1_EXTI1                                      (0x01U << EXTI_CR1_EXTI1_Pos)
#define	EXTI_CR1_EXTI2_Pos                                  (11)
#define	EXTI_CR1_EXTI2                                      (0x02U << EXTI_CR1_EXTI2_Pos)
#define	EXTI_CR1_EXTI3_Pos                                  (15)
#define	EXTI_CR1_EXTI3                                      (0x03U << EXTI_CR1_EXTI3_Pos)
