#define	EXTI_IMR_IMR0_Pos                                   (0)
#define	EXTI_IMR_IMR0                                       (0x00U << EXTI_IMR_IMR0_Pos)
#define	EXTI_IMR_IMR1_Pos                                   (1)
#define	EXTI_IMR_IMR1                                       (0x01U << EXTI_IMR_IMR1_Pos)
#define	EXTI_IMR_IMR2_Pos                                   (2)
#define	EXTI_IMR_IMR2                                       (0x02U << EXTI_IMR_IMR2_Pos)
#define	EXTI_IMR_IMR3_Pos                                   (3)
#define	EXTI_IMR_IMR3                                       (0x03U << EXTI_IMR_IMR3_Pos)
#define	EXTI_IMR_IMR4_Pos                                   (4)
#define	EXTI_IMR_IMR4                                       (0x04U << EXTI_IMR_IMR4_Pos)
#define	EXTI_IMR_IMR5_Pos                                   (5)
#define	EXTI_IMR_IMR5                                       (0x05U << EXTI_IMR_IMR5_Pos)
#define	EXTI_IMR_IMR6_Pos                                   (6)
#define	EXTI_IMR_IMR6                                       (0x06U << EXTI_IMR_IMR6_Pos)
#define	EXTI_IMR_IMR7_Pos                                   (7)
#define	EXTI_IMR_IMR7                                       (0x07U << EXTI_IMR_IMR7_Pos)
#define	EXTI_IMR_IMR8_Pos                                   (8)
#define	EXTI_IMR_IMR8                                       (0x08U << EXTI_IMR_IMR8_Pos)
#define	EXTI_IMR_IMR9_Pos                                   (9)
#define	EXTI_IMR_IMR9                                       (0x09U << EXTI_IMR_IMR9_Pos)
#define	EXTI_IMR_IMR10_Pos                                  (10)
#define	EXTI_IMR_IMR10                                      (0x0AU << EXTI_IMR_IMR10_Pos)
#define	EXTI_IMR_IMR11_Pos                                  (11)
#define	EXTI_IMR_IMR11                                      (0x0BU << EXTI_IMR_IMR11_Pos)
#define	EXTI_IMR_IMR12_Pos                                  (12)
#define	EXTI_IMR_IMR12                                      (0x0CU << EXTI_IMR_IMR12_Pos)
#define	EXTI_IMR_IMR13_Pos                                  (13)
#define	EXTI_IMR_IMR13                                      (0x0DU << EXTI_IMR_IMR13_Pos)
#define	EXTI_IMR_IMR14_Pos                                  (14)
#define	EXTI_IMR_IMR14                                      (0x0EU << EXTI_IMR_IMR14_Pos)
#define	EXTI_IMR_IMR15_Pos                                  (15)
#define	EXTI_IMR_IMR15                                      (0x0FU << EXTI_IMR_IMR15_Pos)
#define	EXTI_IMR_IMR16_Pos                                  (16)
#define	EXTI_IMR_IMR16                                      (0x010U << EXTI_IMR_IMR16_Pos)
#define	EXTI_IMR_IMR17_Pos                                  (17)
#define	EXTI_IMR_IMR17                                      (0x011U << EXTI_IMR_IMR17_Pos)
#define	EXTI_IMR_IMR18_Pos                                  (18)
#define	EXTI_IMR_IMR18                                      (0x012U << EXTI_IMR_IMR18_Pos)
