#define	EXTI_MAPR_SPI1_Pos                                  (0)
#define	EXTI_MAPR_SPI1                                      (0x00U << EXTI_MAPR_SPI1_Pos)
#define	EXTI_MAPR_I2C1_Pos                                  (1)
#define	EXTI_MAPR_I2C1                                      (0x01U << EXTI_MAPR_I2C1_Pos)
#define	EXTI_MAPR_UART1_Pos                                 (2)
#define	EXTI_MAPR_UART1                                     (0x02U << EXTI_MAPR_UART1_Pos)
#define	EXTI_MAPR_UART3_Pos                                 (5)
#define	EXTI_MAPR_UART3                                     (0x04U << EXTI_MAPR_UART3_Pos)
#define	EXTI_MAPR_TIM1_Pos                                  (7)
#define	EXTI_MAPR_TIM1                                      (0x05U << EXTI_MAPR_TIM1_Pos)
#define	EXTI_MAPR_TIM2_Pos                                  (9)
#define	EXTI_MAPR_TIM2                                      (0x06U << EXTI_MAPR_TIM2_Pos)
#define	EXTI_MAPR_TIM3_Pos                                  (11)
#define	EXTI_MAPR_TIM3                                      (0x07U << EXTI_MAPR_TIM3_Pos)
#define	EXTI_MAPR_CAN_Pos                                   (14)
#define	EXTI_MAPR_CAN                                       (0x09U << EXTI_MAPR_CAN_Pos)
#define	EXTI_MAPR_PD01_Pos                                  (15)
#define	EXTI_MAPR_PD01                                      (0x0AU << EXTI_MAPR_PD01_Pos)
#define	EXTI_MAPR_SWJ_Pos                                   (26)
#define	EXTI_MAPR_SWJ                                       (0x0CU << EXTI_MAPR_SWJ_Pos)
