#define	EXTI_PR_PR0_Pos                                     (0)
#define	EXTI_PR_PR0                                         (0x00U << EXTI_PR_PR0_Pos)
#define	EXTI_PR_PR1_Pos                                     (1)
#define	EXTI_PR_PR1                                         (0x01U << EXTI_PR_PR1_Pos)
#define	EXTI_PR_PR2_Pos                                     (2)
#define	EXTI_PR_PR2                                         (0x02U << EXTI_PR_PR2_Pos)
#define	EXTI_PR_PR3_Pos                                     (3)
#define	EXTI_PR_PR3                                         (0x03U << EXTI_PR_PR3_Pos)
#define	EXTI_PR_PR4_Pos                                     (4)
#define	EXTI_PR_PR4                                         (0x04U << EXTI_PR_PR4_Pos)
#define	EXTI_PR_PR5_Pos                                     (5)
#define	EXTI_PR_PR5                                         (0x05U << EXTI_PR_PR5_Pos)
#define	EXTI_PR_PR6_Pos                                     (6)
#define	EXTI_PR_PR6                                         (0x06U << EXTI_PR_PR6_Pos)
#define	EXTI_PR_PR7_Pos                                     (7)
#define	EXTI_PR_PR7                                         (0x07U << EXTI_PR_PR7_Pos)
#define	EXTI_PR_PR8_Pos                                     (8)
#define	EXTI_PR_PR8                                         (0x08U << EXTI_PR_PR8_Pos)
#define	EXTI_PR_PR9_Pos                                     (9)
#define	EXTI_PR_PR9                                         (0x09U << EXTI_PR_PR9_Pos)
#define	EXTI_PR_PR10_Pos                                    (10)
#define	EXTI_PR_PR10                                        (0x0AU << EXTI_PR_PR10_Pos)
#define	EXTI_PR_PR11_Pos                                    (11)
#define	EXTI_PR_PR11                                        (0x0BU << EXTI_PR_PR11_Pos)
#define	EXTI_PR_PR12_Pos                                    (12)
#define	EXTI_PR_PR12                                        (0x0CU << EXTI_PR_PR12_Pos)
#define	EXTI_PR_PR13_Pos                                    (13)
#define	EXTI_PR_PR13                                        (0x0DU << EXTI_PR_PR13_Pos)
#define	EXTI_PR_PR14_Pos                                    (14)
#define	EXTI_PR_PR14                                        (0x0EU << EXTI_PR_PR14_Pos)
#define	EXTI_PR_PR15_Pos                                    (15)
#define	EXTI_PR_PR15                                        (0x0FU << EXTI_PR_PR15_Pos)
#define	EXTI_PR_PR16_Pos                                    (16)
#define	EXTI_PR_PR16                                        (0x010U << EXTI_PR_PR16_Pos)
#define	EXTI_PR_PR17_Pos                                    (17)
#define	EXTI_PR_PR17                                        (0x011U << EXTI_PR_PR17_Pos)
#define	EXTI_PR_PR18_Pos                                    (18)
#define	EXTI_PR_PR18                                        (0x012U << EXTI_PR_PR18_Pos)
