#define	EXTI_SWIER_SWIER0_Pos                               (0)
#define	EXTI_SWIER_SWIER0                                   (0x00U << EXTI_SWIER_SWIER0_Pos)
#define	EXTI_SWIER_SWIER1_Pos                               (1)
#define	EXTI_SWIER_SWIER1                                   (0x01U << EXTI_SWIER_SWIER1_Pos)
#define	EXTI_SWIER_SWIER2_Pos                               (2)
#define	EXTI_SWIER_SWIER2                                   (0x02U << EXTI_SWIER_SWIER2_Pos)
#define	EXTI_SWIER_SWIER3_Pos                               (3)
#define	EXTI_SWIER_SWIER3                                   (0x03U << EXTI_SWIER_SWIER3_Pos)
#define	EXTI_SWIER_SWIER4_Pos                               (4)
#define	EXTI_SWIER_SWIER4                                   (0x04U << EXTI_SWIER_SWIER4_Pos)
#define	EXTI_SWIER_SWIER5_Pos                               (5)
#define	EXTI_SWIER_SWIER5                                   (0x05U << EXTI_SWIER_SWIER5_Pos)
#define	EXTI_SWIER_SWIER6_Pos                               (6)
#define	EXTI_SWIER_SWIER6                                   (0x06U << EXTI_SWIER_SWIER6_Pos)
#define	EXTI_SWIER_SWIER7_Pos                               (7)
#define	EXTI_SWIER_SWIER7                                   (0x07U << EXTI_SWIER_SWIER7_Pos)
#define	EXTI_SWIER_SWIER8_Pos                               (8)
#define	EXTI_SWIER_SWIER8                                   (0x08U << EXTI_SWIER_SWIER8_Pos)
#define	EXTI_SWIER_SWIER9_Pos                               (9)
#define	EXTI_SWIER_SWIER9                                   (0x09U << EXTI_SWIER_SWIER9_Pos)
#define	EXTI_SWIER_SWIER10_Pos                              (10)
#define	EXTI_SWIER_SWIER10                                  (0x0AU << EXTI_SWIER_SWIER10_Pos)
#define	EXTI_SWIER_SWIER11_Pos                              (11)
#define	EXTI_SWIER_SWIER11                                  (0x0BU << EXTI_SWIER_SWIER11_Pos)
#define	EXTI_SWIER_SWIER12_Pos                              (12)
#define	EXTI_SWIER_SWIER12                                  (0x0CU << EXTI_SWIER_SWIER12_Pos)
#define	EXTI_SWIER_SWIER13_Pos                              (13)
#define	EXTI_SWIER_SWIER13                                  (0x0DU << EXTI_SWIER_SWIER13_Pos)
#define	EXTI_SWIER_SWIER14_Pos                              (14)
#define	EXTI_SWIER_SWIER14                                  (0x0EU << EXTI_SWIER_SWIER14_Pos)
#define	EXTI_SWIER_SWIER15_Pos                              (15)
#define	EXTI_SWIER_SWIER15                                  (0x0FU << EXTI_SWIER_SWIER15_Pos)
#define	EXTI_SWIER_SWIER16_Pos                              (16)
#define	EXTI_SWIER_SWIER16                                  (0x010U << EXTI_SWIER_SWIER16_Pos)
#define	EXTI_SWIER_SWIER17_Pos                              (17)
#define	EXTI_SWIER_SWIER17                                  (0x011U << EXTI_SWIER_SWIER17_Pos)
#define	EXTI_SWIER_SWIER18_Pos                              (18)
#define	EXTI_SWIER_SWIER18                                  (0x012U << EXTI_SWIER_SWIER18_Pos)
