#define	_ok_RCC_RCC_1_CFGR_SW_Pos                           (1)
#define	_ok_RCC_RCC_1_CFGR_SW                               (0x00U << _ok_RCC_RCC_1_CFGR_SW_Pos)
#define	_ok_RCC_RCC_1_CFGR_SWS_Pos                          (3)
#define	_ok_RCC_RCC_1_CFGR_SWS                              (0x01U << _ok_RCC_RCC_1_CFGR_SWS_Pos)
#define	_ok_RCC_RCC_1_CFGR_HPRE_Pos                         (7)
#define	_ok_RCC_RCC_1_CFGR_HPRE                             (0x02U << _ok_RCC_RCC_1_CFGR_HPRE_Pos)
#define	_ok_RCC_RCC_1_CFGR_PPRE1_Pos                        (10)
#define	_ok_RCC_RCC_1_CFGR_PPRE1                            (0x03U << _ok_RCC_RCC_1_CFGR_PPRE1_Pos)
#define	_ok_RCC_RCC_1_CFGR_PPRE2_Pos                        (13)
#define	_ok_RCC_RCC_1_CFGR_PPRE2                            (0x04U << _ok_RCC_RCC_1_CFGR_PPRE2_Pos)
#define	_ok_RCC_RCC_1_CFGR_PLLSRC_Pos                       (16)
#define	_ok_RCC_RCC_1_CFGR_PLLSRC                           (0x06U << _ok_RCC_RCC_1_CFGR_PLLSRC_Pos)
#define	_ok_RCC_RCC_1_CFGR_SRCDIV_Pos                       (17)
#define	_ok_RCC_RCC_1_CFGR_SRCDIV                           (0x07U << _ok_RCC_RCC_1_CFGR_SRCDIV_Pos)
#define	_ok_RCC_RCC_1_CFGR_USBPRE_Pos                       (23)
#define	_ok_RCC_RCC_1_CFGR_USBPRE                           (0x09U << _ok_RCC_RCC_1_CFGR_USBPRE_Pos)
#define	_ok_RCC_RCC_1_CFGR_MCO_Pos                          (26)
#define	_ok_RCC_RCC_1_CFGR_MCO                              (0x0AU << _ok_RCC_RCC_1_CFGR_MCO_Pos)
