#define	_ok_RCC_RCC_9_CSR_LSION_Pos                         (0)
#define	_ok_RCC_RCC_9_CSR_LSION                             (0x00U << _ok_RCC_RCC_9_CSR_LSION_Pos)
#define	_ok_RCC_RCC_9_CSR_LSIRDY_Pos                        (1)
#define	_ok_RCC_RCC_9_CSR_LSIRDY                            (0x01U << _ok_RCC_RCC_9_CSR_LSIRDY_Pos)
#define	_ok_RCC_RCC_9_CSR_CLR_Pos                           (24)
#define	_ok_RCC_RCC_9_CSR_CLR                               (0x04U << _ok_RCC_RCC_9_CSR_CLR_Pos)
#define	_ok_RCC_RCC_9_CSR_RSTF_Pos                          (26)
#define	_ok_RCC_RCC_9_CSR_RSTF                              (0x06U << _ok_RCC_RCC_9_CSR_RSTF_Pos)
#define	_ok_RCC_RCC_9_CSR_PORF_Pos                          (27)
#define	_ok_RCC_RCC_9_CSR_PORF                              (0x07U << _ok_RCC_RCC_9_CSR_PORF_Pos)
#define	_ok_RCC_RCC_9_CSR_SWRSTF_Pos                        (28)
#define	_ok_RCC_RCC_9_CSR_SWRSTF                            (0x08U << _ok_RCC_RCC_9_CSR_SWRSTF_Pos)
#define	_ok_RCC_RCC_9_CSR_IWDGF_Pos                         (29)
#define	_ok_RCC_RCC_9_CSR_IWDGF                             (0x09U << _ok_RCC_RCC_9_CSR_IWDGF_Pos)
#define	_ok_RCC_RCC_9_CSR_WWDGF_Pos                         (30)
#define	_ok_RCC_RCC_9_CSR_WWDGF                             (0x0AU << _ok_RCC_RCC_9_CSR_WWDGF_Pos)
