#define	_ok_RCC_RCC_0_CR_HSION_Pos                          (0)
#define	_ok_RCC_RCC_0_CR_HSION                              (0x00U << _ok_RCC_RCC_0_CR_HSION_Pos)
#define	_ok_RCC_RCC_0_CR_HSIRDY_Pos                         (1)
#define	_ok_RCC_RCC_0_CR_HSIRDY                             (0x01U << _ok_RCC_RCC_0_CR_HSIRDY_Pos)
#define	_ok_RCC_RCC_0_CR_HSICAL_Pos                         (15)
#define	_ok_RCC_RCC_0_CR_HSICAL                             (0x03U << _ok_RCC_RCC_0_CR_HSICAL_Pos)
#define	_ok_RCC_RCC_0_CR_HSEON_Pos                          (16)
#define	_ok_RCC_RCC_0_CR_HSEON                              (0x04U << _ok_RCC_RCC_0_CR_HSEON_Pos)
#define	_ok_RCC_RCC_0_CR_HSERDY_Pos                         (17)
#define	_ok_RCC_RCC_0_CR_HSERDY                             (0x05U << _ok_RCC_RCC_0_CR_HSERDY_Pos)
#define	_ok_RCC_RCC_0_CR_BYPASS_Pos                         (18)
#define	_ok_RCC_RCC_0_CR_BYPASS                             (0x06U << _ok_RCC_RCC_0_CR_BYPASS_Pos)
#define	_ok_RCC_RCC_0_CR_CSSON_Pos                          (19)
#define	_ok_RCC_RCC_0_CR_CSSON                              (0x07U << _ok_RCC_RCC_0_CR_CSSON_Pos)
#define	_ok_RCC_RCC_0_CR_PLLDIV_Pos                         (22)
#define	_ok_RCC_RCC_0_CR_PLLDIV                             (0x08U << _ok_RCC_RCC_0_CR_PLLDIV_Pos)
#define	_ok_RCC_RCC_0_CR_PLLON_Pos                          (24)
#define	_ok_RCC_RCC_0_CR_PLLON                              (0x0AU << _ok_RCC_RCC_0_CR_PLLON_Pos)
#define	_ok_RCC_RCC_0_CR_PLLRDY_Pos                         (25)
#define	_ok_RCC_RCC_0_CR_PLLRDY                             (0x0BU << _ok_RCC_RCC_0_CR_PLLRDY_Pos)
#define	_ok_RCC_RCC_0_CR_PLLMUL_Pos                         (31)
#define	_ok_RCC_RCC_0_CR_PLLMUL                             (0x0CU << _ok_RCC_RCC_0_CR_PLLMUL_Pos)
