#define	_ok_RCC_RCC_2_CIR_LSIF_Pos                          (0)
#define	_ok_RCC_RCC_2_CIR_LSIF                              (0x00U << _ok_RCC_RCC_2_CIR_LSIF_Pos)
#define	_ok_RCC_RCC_2_CIR_LSEF_Pos                          (1)
#define	_ok_RCC_RCC_2_CIR_LSEF                              (0x01U << _ok_RCC_RCC_2_CIR_LSEF_Pos)
#define	_ok_RCC_RCC_2_CIR_HSIF_Pos                          (2)
#define	_ok_RCC_RCC_2_CIR_HSIF                              (0x02U << _ok_RCC_RCC_2_CIR_HSIF_Pos)
#define	_ok_RCC_RCC_2_CIR_HSEF_Pos                          (3)
#define	_ok_RCC_RCC_2_CIR_HSEF                              (0x03U << _ok_RCC_RCC_2_CIR_HSEF_Pos)
#define	_ok_RCC_RCC_2_CIR_PLLF_Pos                          (4)
#define	_ok_RCC_RCC_2_CIR_PLLF                              (0x04U << _ok_RCC_RCC_2_CIR_PLLF_Pos)
#define	_ok_RCC_RCC_2_CIR_CSSF_Pos                          (7)
#define	_ok_RCC_RCC_2_CIR_CSSF                              (0x06U << _ok_RCC_RCC_2_CIR_CSSF_Pos)
#define	_ok_RCC_RCC_2_CIR_LSIIE_Pos                         (8)
#define	_ok_RCC_RCC_2_CIR_LSIIE                             (0x07U << _ok_RCC_RCC_2_CIR_LSIIE_Pos)
#define	_ok_RCC_RCC_2_CIR_LSEIE_Pos                         (9)
#define	_ok_RCC_RCC_2_CIR_LSEIE                             (0x08U << _ok_RCC_RCC_2_CIR_LSEIE_Pos)
#define	_ok_RCC_RCC_2_CIR_HSIIE_Pos                         (10)
#define	_ok_RCC_RCC_2_CIR_HSIIE                             (0x09U << _ok_RCC_RCC_2_CIR_HSIIE_Pos)
#define	_ok_RCC_RCC_2_CIR_HSEIE_Pos                         (11)
#define	_ok_RCC_RCC_2_CIR_HSEIE                             (0x0AU << _ok_RCC_RCC_2_CIR_HSEIE_Pos)
#define	_ok_RCC_RCC_2_CIR_PLLIE_Pos                         (12)
#define	_ok_RCC_RCC_2_CIR_PLLIE                             (0x0BU << _ok_RCC_RCC_2_CIR_PLLIE_Pos)
#define	_ok_RCC_RCC_2_CIR_LSIC_Pos                          (16)
#define	_ok_RCC_RCC_2_CIR_LSIC                              (0x0DU << _ok_RCC_RCC_2_CIR_LSIC_Pos)
#define	_ok_RCC_RCC_2_CIR_LSEC_Pos                          (17)
#define	_ok_RCC_RCC_2_CIR_LSEC                              (0x0EU << _ok_RCC_RCC_2_CIR_LSEC_Pos)
#define	_ok_RCC_RCC_2_CIR_HSIC_Pos                          (18)
#define	_ok_RCC_RCC_2_CIR_HSIC                              (0x0FU << _ok_RCC_RCC_2_CIR_HSIC_Pos)
#define	_ok_RCC_RCC_2_CIR_HSEC_Pos                          (19)
#define	_ok_RCC_RCC_2_CIR_HSEC                              (0x010U << _ok_RCC_RCC_2_CIR_HSEC_Pos)
#define	_ok_RCC_RCC_2_CIR_PLLC_Pos                          (20)
#define	_ok_RCC_RCC_2_CIR_PLLC                              (0x011U << _ok_RCC_RCC_2_CIR_PLLC_Pos)
#define	_ok_RCC_RCC_2_CIR_CSSC_Pos                          (23)
#define	_ok_RCC_RCC_2_CIR_CSSC                              (0x013U << _ok_RCC_RCC_2_CIR_CSSC_Pos)
