#define	_ok_RCC_RCC_3_APB2RSTR_AFIO_Pos                     (0)
#define	_ok_RCC_RCC_3_APB2RSTR_AFIO                         (0x00U << _ok_RCC_RCC_3_APB2RSTR_AFIO_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_PORTA_Pos                    (2)
#define	_ok_RCC_RCC_3_APB2RSTR_PORTA                        (0x02U << _ok_RCC_RCC_3_APB2RSTR_PORTA_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_PORTB_Pos                    (3)
#define	_ok_RCC_RCC_3_APB2RSTR_PORTB                        (0x03U << _ok_RCC_RCC_3_APB2RSTR_PORTB_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_PORTC_Pos                    (4)
#define	_ok_RCC_RCC_3_APB2RSTR_PORTC                        (0x04U << _ok_RCC_RCC_3_APB2RSTR_PORTC_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_PORTD_Pos                    (5)
#define	_ok_RCC_RCC_3_APB2RSTR_PORTD                        (0x05U << _ok_RCC_RCC_3_APB2RSTR_PORTD_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_ADC1_Pos                     (9)
#define	_ok_RCC_RCC_3_APB2RSTR_ADC1                         (0x07U << _ok_RCC_RCC_3_APB2RSTR_ADC1_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_ADC2_Pos                     (10)
#define	_ok_RCC_RCC_3_APB2RSTR_ADC2                         (0x08U << _ok_RCC_RCC_3_APB2RSTR_ADC2_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_TIM1_Pos                     (11)
#define	_ok_RCC_RCC_3_APB2RSTR_TIM1                         (0x09U << _ok_RCC_RCC_3_APB2RSTR_TIM1_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_SPI1_Pos                     (12)
#define	_ok_RCC_RCC_3_APB2RSTR_SPI1                         (0x0AU << _ok_RCC_RCC_3_APB2RSTR_SPI1_Pos)
#define	_ok_RCC_RCC_3_APB2RSTR_UART1_Pos                    (14)
#define	_ok_RCC_RCC_3_APB2RSTR_UART1                        (0x0CU << _ok_RCC_RCC_3_APB2RSTR_UART1_Pos)
