#define	I2C_CR_EN_Pos                                       (0)
#define	I2C_CR_EN                                           (0x00U << I2C_CR_EN_Pos)
#define	I2C_CR_START_Pos                                    (1)
#define	I2C_CR_START                                        (0x01U << I2C_CR_START_Pos)
#define	I2C_CR_STOP_Pos                                     (2)
#define	I2C_CR_STOP                                         (0x02U << I2C_CR_STOP_Pos)
#define	I2C_CR_INT_Pos                                      (3)
#define	I2C_CR_INT                                          (0x03U << I2C_CR_INT_Pos)
#define	I2C_CR_AA_Pos                                       (4)
#define	I2C_CR_AA                                           (0x04U << I2C_CR_AA_Pos)
#define	I2C_CR_SRC_Pos                                      (6)
#define	I2C_CR_SRC                                          (0x05U << I2C_CR_SRC_Pos)
