#define	I2C_ADDR_GC_Pos                                     (0)
#define	I2C_ADDR_GC                                         (0x00U << I2C_ADDR_GC_Pos)
#define	I2C_ADDR_ADR0_Pos                                   (7)
#define	I2C_ADDR_ADR0                                       (0x01U << I2C_ADDR_ADR0_Pos)
#define	I2C_ADDR_EN1_Pos                                    (8)
#define	I2C_ADDR_EN1                                        (0x02U << I2C_ADDR_EN1_Pos)
#define	I2C_ADDR_ADR1_Pos                                   (15)
#define	I2C_ADDR_ADR1                                       (0x03U << I2C_ADDR_ADR1_Pos)
#define	I2C_ADDR_EN2_Pos                                    (16)
#define	I2C_ADDR_EN2                                        (0x04U << I2C_ADDR_EN2_Pos)
#define	I2C_ADDR_ADR2_Pos                                   (23)
#define	I2C_ADDR_ADR2                                       (0x05U << I2C_ADDR_ADR2_Pos)
#define	I2C_ADDR_EN3_Pos                                    (24)
#define	I2C_ADDR_EN3                                        (0x06U << I2C_ADDR_EN3_Pos)
#define	I2C_ADDR_ADR3_Pos                                   (31)
#define	I2C_ADDR_ADR3                                       (0x07U << I2C_ADDR_ADR3_Pos)
