#define	I2C_CR_v2_MASTER_Pos                                (0)
#define	I2C_CR_v2_MASTER                                    (0x00U << I2C_CR_v2_MASTER_Pos)
#define	I2C_CR_v2_SPEED_Pos                                 (2)
#define	I2C_CR_v2_SPEED                                     (0x01U << I2C_CR_v2_SPEED_Pos)
#define	I2C_CR_v2_SLAVE10_Pos                               (3)
#define	I2C_CR_v2_SLAVE10                                   (0x02U << I2C_CR_v2_SLAVE10_Pos)
#define	I2C_CR_v2_MASTER10_Pos                              (4)
#define	I2C_CR_v2_MASTER10                                  (0x03U << I2C_CR_v2_MASTER10_Pos)
#define	I2C_CR_v2_REPEN_Pos                                 (5)
#define	I2C_CR_v2_REPEN                                     (0x04U << I2C_CR_v2_REPEN_Pos)
#define	I2C_CR_v2_SLAVEDIS_Pos                              (6)
#define	I2C_CR_v2_SLAVEDIS                                  (0x05U << I2C_CR_v2_SLAVEDIS_Pos)
#define	I2C_CR_v2_STOPINT_Pos                               (7)
#define	I2C_CR_v2_STOPINT                                   (0x06U << I2C_CR_v2_STOPINT_Pos)
#define	I2C_CR_v2_EMPINT_Pos                                (8)
#define	I2C_CR_v2_EMPINT                                    (0x07U << I2C_CR_v2_EMPINT_Pos)
