#define	I2C_RAWISR_RX_UNDER_Pos                             (0)
#define	I2C_RAWISR_RX_UNDER                                 (0x00U << I2C_RAWISR_RX_UNDER_Pos)
#define	I2C_RAWISR_RX_OVER_Pos                              (1)
#define	I2C_RAWISR_RX_OVER                                  (0x01U << I2C_RAWISR_RX_OVER_Pos)
#define	I2C_RAWISR_RX_FULL_Pos                              (2)
#define	I2C_RAWISR_RX_FULL                                  (0x02U << I2C_RAWISR_RX_FULL_Pos)
#define	I2C_RAWISR_TX_OVER_Pos                              (3)
#define	I2C_RAWISR_TX_OVER                                  (0x03U << I2C_RAWISR_TX_OVER_Pos)
#define	I2C_RAWISR_TX_EMPTY_Pos                             (4)
#define	I2C_RAWISR_TX_EMPTY                                 (0x04U << I2C_RAWISR_TX_EMPTY_Pos)
#define	I2C_RAWISR_RX_REQ_Pos                               (5)
#define	I2C_RAWISR_RX_REQ                                   (0x05U << I2C_RAWISR_RX_REQ_Pos)
#define	I2C_RAWISR_TX_ABRT_Pos                              (6)
#define	I2C_RAWISR_TX_ABRT                                  (0x06U << I2C_RAWISR_TX_ABRT_Pos)
#define	I2C_RAWISR_RX_DONE_Pos                              (7)
#define	I2C_RAWISR_RX_DONE                                  (0x07U << I2C_RAWISR_RX_DONE_Pos)
#define	I2C_RAWISR_ACTIV_Pos                                (8)
#define	I2C_RAWISR_ACTIV                                    (0x08U << I2C_RAWISR_ACTIV_Pos)
#define	I2C_RAWISR_STOP_Pos                                 (9)
#define	I2C_RAWISR_STOP                                     (0x09U << I2C_RAWISR_STOP_Pos)
#define	I2C_RAWISR_START_Pos                                (10)
#define	I2C_RAWISR_START                                    (0x0AU << I2C_RAWISR_START_Pos)
#define	I2C_RAWISR_GC_Pos                                   (11)
#define	I2C_RAWISR_GC                                       (0x0BU << I2C_RAWISR_GC_Pos)
