#define	I2C_SR_ACTIV_Pos                                    (0)
#define	I2C_SR_ACTIV                                        (0x00U << I2C_SR_ACTIV_Pos)
#define	I2C_SR_TFNF_Pos                                     (1)
#define	I2C_SR_TFNF                                         (0x01U << I2C_SR_TFNF_Pos)
#define	I2C_SR_TFE_Pos                                      (2)
#define	I2C_SR_TFE                                          (0x02U << I2C_SR_TFE_Pos)
#define	I2C_SR_RFNE_Pos                                     (3)
#define	I2C_SR_RFNE                                         (0x03U << I2C_SR_RFNE_Pos)
#define	I2C_SR_RFF_Pos                                      (4)
#define	I2C_SR_RFF                                          (0x04U << I2C_SR_RFF_Pos)
#define	I2C_SR_MST_ACTIV_Pos                                (5)
#define	I2C_SR_MST_ACTIV                                    (0x05U << I2C_SR_MST_ACTIV_Pos)
#define	I2C_SR_SLV_ACTIV_Pos                                (6)
#define	I2C_SR_SLV_ACTIV                                    (0x06U << I2C_SR_SLV_ACTIV_Pos)
