#define	DMA_CCRx_EN_Pos                                     (0)
#define	DMA_CCRx_EN                                         (0x00U << DMA_CCRx_EN_Pos)
#define	DMA_CCRx_TCIE_Pos                                   (1)
#define	DMA_CCRx_TCIE                                       (0x01U << DMA_CCRx_TCIE_Pos)
#define	DMA_CCRx_HTIE_Pos                                   (2)
#define	DMA_CCRx_HTIE                                       (0x02U << DMA_CCRx_HTIE_Pos)
#define	DMA_CCRx_TEIE_Pos                                   (3)
#define	DMA_CCRx_TEIE                                       (0x03U << DMA_CCRx_TEIE_Pos)
#define	DMA_CCRx_DIR_Pos                                    (4)
#define	DMA_CCRx_DIR                                        (0x04U << DMA_CCRx_DIR_Pos)
#define	DMA_CCRx_CIRC_Pos                                   (5)
#define	DMA_CCRx_CIRC                                       (0x05U << DMA_CCRx_CIRC_Pos)
#define	DMA_CCRx_PINC_Pos                                   (6)
#define	DMA_CCRx_PINC                                       (0x06U << DMA_CCRx_PINC_Pos)
#define	DMA_CCRx_MINC_Pos                                   (7)
#define	DMA_CCRx_MINC                                       (0x07U << DMA_CCRx_MINC_Pos)
#define	DMA_CCRx_PSIZE_Pos                                  (9)
#define	DMA_CCRx_PSIZE                                      (0x08U << DMA_CCRx_PSIZE_Pos)
#define	DMA_CCRx_MSIZE_Pos                                  (11)
#define	DMA_CCRx_MSIZE                                      (0x09U << DMA_CCRx_MSIZE_Pos)
#define	DMA_CCRx_PL_Pos                                     (13)
#define	DMA_CCRx_PL                                         (0x0AU << DMA_CCRx_PL_Pos)
#define	DMA_CCRx_M2M_Pos                                    (14)
#define	DMA_CCRx_M2M                                        (0x0BU << DMA_CCRx_M2M_Pos)
