#define	DMA_IFCR_CGIF1_Pos                                  (0)
#define	DMA_IFCR_CGIF1                                      (0x00U << DMA_IFCR_CGIF1_Pos)
#define	DMA_IFCR_CTCIF1_Pos                                 (1)
#define	DMA_IFCR_CTCIF1                                     (0x01U << DMA_IFCR_CTCIF1_Pos)
#define	DMA_IFCR_CHTIF1_Pos                                 (2)
#define	DMA_IFCR_CHTIF1                                     (0x02U << DMA_IFCR_CHTIF1_Pos)
#define	DMA_IFCR_CTEIF1_Pos                                 (3)
#define	DMA_IFCR_CTEIF1                                     (0x03U << DMA_IFCR_CTEIF1_Pos)
#define	DMA_IFCR_CGIF2_Pos                                  (4)
#define	DMA_IFCR_CGIF2                                      (0x04U << DMA_IFCR_CGIF2_Pos)
#define	DMA_IFCR_CTCIF2_Pos                                 (5)
#define	DMA_IFCR_CTCIF2                                     (0x05U << DMA_IFCR_CTCIF2_Pos)
#define	DMA_IFCR_CHTIF2_Pos                                 (6)
#define	DMA_IFCR_CHTIF2                                     (0x06U << DMA_IFCR_CHTIF2_Pos)
#define	DMA_IFCR_CTEIF2_Pos                                 (7)
#define	DMA_IFCR_CTEIF2                                     (0x07U << DMA_IFCR_CTEIF2_Pos)
#define	DMA_IFCR_CGIF3_Pos                                  (8)
#define	DMA_IFCR_CGIF3                                      (0x08U << DMA_IFCR_CGIF3_Pos)
#define	DMA_IFCR_CTCIF3_Pos                                 (9)
#define	DMA_IFCR_CTCIF3                                     (0x09U << DMA_IFCR_CTCIF3_Pos)
#define	DMA_IFCR_CHTIF3_Pos                                 (10)
#define	DMA_IFCR_CHTIF3                                     (0x0AU << DMA_IFCR_CHTIF3_Pos)
#define	DMA_IFCR_CTEIF3_Pos                                 (11)
#define	DMA_IFCR_CTEIF3                                     (0x0BU << DMA_IFCR_CTEIF3_Pos)
#define	DMA_IFCR_CGIF4_Pos                                  (12)
#define	DMA_IFCR_CGIF4                                      (0x0CU << DMA_IFCR_CGIF4_Pos)
#define	DMA_IFCR_CTCIF4_Pos                                 (13)
#define	DMA_IFCR_CTCIF4                                     (0x0DU << DMA_IFCR_CTCIF4_Pos)
#define	DMA_IFCR_CHTIF4_Pos                                 (14)
#define	DMA_IFCR_CHTIF4                                     (0x0EU << DMA_IFCR_CHTIF4_Pos)
#define	DMA_IFCR_CTEIF4_Pos                                 (15)
#define	DMA_IFCR_CTEIF4                                     (0x0FU << DMA_IFCR_CTEIF4_Pos)
#define	DMA_IFCR_CGIF5_Pos                                  (16)
#define	DMA_IFCR_CGIF5                                      (0x010U << DMA_IFCR_CGIF5_Pos)
#define	DMA_IFCR_CTCIF5_Pos                                 (17)
#define	DMA_IFCR_CTCIF5                                     (0x011U << DMA_IFCR_CTCIF5_Pos)
#define	DMA_IFCR_CHTIF5_Pos                                 (18)
#define	DMA_IFCR_CHTIF5                                     (0x012U << DMA_IFCR_CHTIF5_Pos)
#define	DMA_IFCR_CTEIF5_Pos                                 (19)
#define	DMA_IFCR_CTEIF5                                     (0x013U << DMA_IFCR_CTEIF5_Pos)
#define	DMA_IFCR_CGIF6_Pos                                  (20)
#define	DMA_IFCR_CGIF6                                      (0x014U << DMA_IFCR_CGIF6_Pos)
#define	DMA_IFCR_CTCIF6_Pos                                 (21)
#define	DMA_IFCR_CTCIF6                                     (0x015U << DMA_IFCR_CTCIF6_Pos)
#define	DMA_IFCR_CHTIF6_Pos                                 (22)
#define	DMA_IFCR_CHTIF6                                     (0x016U << DMA_IFCR_CHTIF6_Pos)
#define	DMA_IFCR_CTEIF6_Pos                                 (23)
#define	DMA_IFCR_CTEIF6                                     (0x017U << DMA_IFCR_CTEIF6_Pos)
#define	DMA_IFCR_CGIF7_Pos                                  (24)
#define	DMA_IFCR_CGIF7                                      (0x018U << DMA_IFCR_CGIF7_Pos)
#define	DMA_IFCR_CTCIF7_Pos                                 (25)
#define	DMA_IFCR_CTCIF7                                     (0x019U << DMA_IFCR_CTCIF7_Pos)
#define	DMA_IFCR_CHTIF7_Pos                                 (26)
#define	DMA_IFCR_CHTIF7                                     (0x01AU << DMA_IFCR_CHTIF7_Pos)
#define	DMA_IFCR_CTEIF7_Pos                                 (27)
#define	DMA_IFCR_CTEIF7                                     (0x01BU << DMA_IFCR_CTEIF7_Pos)
