#define	UART_CR_EN_Pos                                      (0)
#define	UART_CR_EN                                          (0x00U << UART_CR_EN_Pos)
#define	UART_CR_DMA_Pos                                     (1)
#define	UART_CR_DMA                                         (0x01U << UART_CR_DMA_Pos)
#define	UART_CR_TXEN_Pos                                    (2)
#define	UART_CR_TXEN                                        (0x02U << UART_CR_TXEN_Pos)
#define	UART_CR_RXEN_Pos                                    (3)
#define	UART_CR_RXEN                                        (0x03U << UART_CR_RXEN_Pos)
#define	UART_CR_BRK_Pos                                     (4)
#define	UART_CR_BRK                                         (0x04U << UART_CR_BRK_Pos)
