#define	UART_DR_DATA_Pos                                    (7)
#define	UART_DR_DATA                                        (0x00U << UART_DR_DATA_Pos)
#define	UART_DR_B9D_Pos                                     (8)
#define	UART_DR_B9D                                         (0x01U << UART_DR_B9D_Pos)
#define	UART_DR_BRK_Pos                                     (9)
#define	UART_DR_BRK                                         (0x02U << UART_DR_BRK_Pos)
