#define	UART_CFGR_MODE_Pos                                  (1)
#define	UART_CFGR_MODE                                      (0x00U << UART_CFGR_MODE_Pos)
#define	UART_CFGR_DFLEN_Pos                                 (3)
#define	UART_CFGR_DFLEN                                     (0x01U << UART_CFGR_DFLEN_Pos)
#define	UART_CFGR_PMOD_Pos                                  (5)
#define	UART_CFGR_PMOD                                      (0x02U << UART_CFGR_PMOD_Pos)
#define	UART_CFGR_STOP_Pos                                  (6)
#define	UART_CFGR_STOP                                      (0x03U << UART_CFGR_STOP_Pos)
#define	UART_CFGR_SWAP_Pos                                  (7)
#define	UART_CFGR_SWAP                                      (0x04U << UART_CFGR_SWAP_Pos)
#define	UART_CFGR_HDUP_Pos                                  (8)
#define	UART_CFGR_HDUP                                      (0x05U << UART_CFGR_HDUP_Pos)
#define	UART_CFGR_CKO_Pos                                   (9)
#define	UART_CFGR_CKO                                       (0x06U << UART_CFGR_CKO_Pos)
#define	UART_CFGR_ABR_Pos                                   (10)
#define	UART_CFGR_ABR                                       (0x07U << UART_CFGR_ABR_Pos)
#define	UART_CFGR_RWU_Pos                                   (11)
#define	UART_CFGR_RWU                                       (0x08U << UART_CFGR_RWU_Pos)
#define	UART_CFGR_WAKE_Pos                                  (12)
#define	UART_CFGR_WAKE                                      (0x09U << UART_CFGR_WAKE_Pos)
#define	UART_CFGR_B9POL_Pos                                 (13)
#define	UART_CFGR_B9POL                                     (0x0AU << UART_CFGR_B9POL_Pos)
#define	UART_CFGR_NACK_Pos                                  (14)
#define	UART_CFGR_NACK                                      (0x0BU << UART_CFGR_NACK_Pos)
#define	UART_CFGR_DIREN_Pos                                 (15)
#define	UART_CFGR_DIREN                                     (0x0CU << UART_CFGR_DIREN_Pos)
#define	UART_CFGR_DIRPOL_Pos                                (16)
#define	UART_CFGR_DIRPOL                                    (0x0DU << UART_CFGR_DIRPOL_Pos)
#define	UART_CFGR_BADD_Pos                                  (18)
#define	UART_CFGR_BADD                                      (0x0EU << UART_CFGR_BADD_Pos)
#define	UART_CFGR_IADD_Pos                                  (20)
#define	UART_CFGR_IADD                                      (0x0FU << UART_CFGR_IADD_Pos)
#define	UART_CFGR_DADD_Pos                                  (22)
#define	UART_CFGR_DADD                                      (0x010U << UART_CFGR_DADD_Pos)
#define	UART_CFGR_GTIME_Pos                                 (31)
#define	UART_CFGR_GTIME                                     (0x012U << UART_CFGR_GTIME_Pos)
