#define	UART_IER_TXE_Pos                                    (0)
#define	UART_IER_TXE                                        (0x00U << UART_IER_TXE_Pos)
#define	UART_IER_TXC_Pos                                    (1)
#define	UART_IER_TXC                                        (0x01U << UART_IER_TXC_Pos)
#define	UART_IER_RXNE_Pos                                   (2)
#define	UART_IER_RXNE                                       (0x02U << UART_IER_RXNE_Pos)
#define	UART_IER_PARITY_Pos                                 (3)
#define	UART_IER_PARITY                                     (0x03U << UART_IER_PARITY_Pos)
#define	UART_IER_OVER_Pos                                   (4)
#define	UART_IER_OVER                                       (0x04U << UART_IER_OVER_Pos)
#define	UART_IER_FRAME_Pos                                  (5)
#define	UART_IER_FRAME                                      (0x05U << UART_IER_FRAME_Pos)
#define	UART_IER_BRK_Pos                                    (6)
#define	UART_IER_BRK                                        (0x06U << UART_IER_BRK_Pos)
#define	UART_IER_B9D_Pos                                    (7)
#define	UART_IER_B9D                                        (0x07U << UART_IER_B9D_Pos)
#define	UART_IER_SYNC_Pos                                   (8)
#define	UART_IER_SYNC                                       (0x08U << UART_IER_SYNC_Pos)
