#define	UART_ISR_TXE_Pos                                    (0)
#define	UART_ISR_TXE                                        (0x00U << UART_ISR_TXE_Pos)
#define	UART_ISR_TXC_Pos                                    (1)
#define	UART_ISR_TXC                                        (0x01U << UART_ISR_TXC_Pos)
#define	UART_ISR_RXNE_Pos                                   (2)
#define	UART_ISR_RXNE                                       (0x02U << UART_ISR_RXNE_Pos)
#define	UART_ISR_PARITY_Pos                                 (3)
#define	UART_ISR_PARITY                                     (0x03U << UART_ISR_PARITY_Pos)
#define	UART_ISR_OVER_Pos                                   (4)
#define	UART_ISR_OVER                                       (0x04U << UART_ISR_OVER_Pos)
#define	UART_ISR_FRAME_Pos                                  (5)
#define	UART_ISR_FRAME                                      (0x05U << UART_ISR_FRAME_Pos)
#define	UART_ISR_BRK_Pos                                    (6)
#define	UART_ISR_BRK                                        (0x06U << UART_ISR_BRK_Pos)
#define	UART_ISR_B9D_Pos                                    (7)
#define	UART_ISR_B9D                                        (0x07U << UART_ISR_B9D_Pos)
#define	UART_ISR_SYNC_Pos                                   (8)
#define	UART_ISR_SYNC                                       (0x08U << UART_ISR_SYNC_Pos)
#define	UART_ISR_STXE_Pos                                   (9)
#define	UART_ISR_STXE                                       (0x09U << UART_ISR_STXE_Pos)
#define	UART_ISR_SRXNE_Pos                                  (10)
#define	UART_ISR_SRXNE                                      (0x0AU << UART_ISR_SRXNE_Pos)
#define	UART_ISR_BADD_Pos                                   (11)
#define	UART_ISR_BADD                                       (0x0BU << UART_ISR_BADD_Pos)
