#define	DAC_CR_EN1_Pos                                      (0)
#define	DAC_CR_EN1                                          (0x00U << DAC_CR_EN1_Pos)
#define	DAC_CR_BOFF1_Pos                                    (1)
#define	DAC_CR_BOFF1                                        (0x01U << DAC_CR_BOFF1_Pos)
#define	DAC_CR_TEN1_Pos                                     (2)
#define	DAC_CR_TEN1                                         (0x02U << DAC_CR_TEN1_Pos)
#define	DAC_CR_TSEL1_Pos                                    (5)
#define	DAC_CR_TSEL1                                        (0x03U << DAC_CR_TSEL1_Pos)
#define	DAC_CR_WAVE1_Pos                                    (7)
#define	DAC_CR_WAVE1                                        (0x04U << DAC_CR_WAVE1_Pos)
#define	DAC_CR_MAMP1_Pos                                    (11)
#define	DAC_CR_MAMP1                                        (0x05U << DAC_CR_MAMP1_Pos)
#define	DAC_CR_DMAEN1_Pos                                   (12)
#define	DAC_CR_DMAEN1                                       (0x06U << DAC_CR_DMAEN1_Pos)
#define	DAC_CR_EN2_Pos                                      (16)
#define	DAC_CR_EN2                                          (0x08U << DAC_CR_EN2_Pos)
#define	DAC_CR_BOFF2_Pos                                    (17)
#define	DAC_CR_BOFF2                                        (0x09U << DAC_CR_BOFF2_Pos)
#define	DAC_CR_TEN2_Pos                                     (18)
#define	DAC_CR_TEN2                                         (0x0AU << DAC_CR_TEN2_Pos)
#define	DAC_CR_TSEL2_Pos                                    (21)
#define	DAC_CR_TSEL2                                        (0x0BU << DAC_CR_TSEL2_Pos)
#define	DAC_CR_WAVE2_Pos                                    (23)
#define	DAC_CR_WAVE2                                        (0x0CU << DAC_CR_WAVE2_Pos)
#define	DAC_CR_MAMP2_Pos                                    (27)
#define	DAC_CR_MAMP2                                        (0x0DU << DAC_CR_MAMP2_Pos)
#define	DAC_CR_DMAEN2_Pos                                   (28)
#define	DAC_CR_DMAEN2                                       (0x0EU << DAC_CR_DMAEN2_Pos)
