#define	DAC_SWTRIGR_SWTRIG1_Pos                             (0)
#define	DAC_SWTRIGR_SWTRIG1                                 (0x00U << DAC_SWTRIGR_SWTRIG1_Pos)
#define	DAC_SWTRIGR_SWTRIG2_Pos                             (1)
#define	DAC_SWTRIGR_SWTRIG2                                 (0x01U << DAC_SWTRIGR_SWTRIG2_Pos)
#define	DAC_SWTRIGR_DACPRE_Pos                              (14)
#define	DAC_SWTRIGR_DACPRE                                  (0x03U << DAC_SWTRIGR_DACPRE_Pos)
