#define	AES_CR_EN_Pos                                       (0)
#define	AES_CR_EN                                           (0x00U << AES_CR_EN_Pos)
#define	AES_CR_DATATYPE_Pos                                 (2)
#define	AES_CR_DATATYPE                                     (0x01U << AES_CR_DATATYPE_Pos)
#define	AES_CR_MODE_Pos                                     (4)
#define	AES_CR_MODE                                         (0x02U << AES_CR_MODE_Pos)
#define	AES_CR_CHMOD[1:0]_Pos                               (6)
#define	AES_CR_CHMOD[1:0]                                   (0x03U << AES_CR_CHMOD[1:0]_Pos)
#define	AES_CR_CCFC_Pos                                     (7)
#define	AES_CR_CCFC                                         (0x04U << AES_CR_CCFC_Pos)
#define	AES_CR_ERRC_Pos                                     (8)
#define	AES_CR_ERRC                                         (0x05U << AES_CR_ERRC_Pos)
#define	AES_CR_CCFIE_Pos                                    (9)
#define	AES_CR_CCFIE                                        (0x06U << AES_CR_CCFIE_Pos)
#define	AES_CR_ERRIE_Pos                                    (10)
#define	AES_CR_ERRIE                                        (0x07U << AES_CR_ERRIE_Pos)
#define	AES_CR_DMAINEN_Pos                                  (11)
#define	AES_CR_DMAINEN                                      (0x08U << AES_CR_DMAINEN_Pos)
#define	AES_CR_DMAOUTEN_Pos                                 (12)
#define	AES_CR_DMAOUTEN                                     (0x09U << AES_CR_DMAOUTEN_Pos)
#define	AES_CR_CHMOD[2]_Pos                                 (16)
#define	AES_CR_CHMOD[2]                                     (0x0BU << AES_CR_CHMOD[2]_Pos)
#define	AES_CR_KSIZE_Pos                                    (19)
#define	AES_CR_KSIZE                                        (0x0DU << AES_CR_KSIZE_Pos)
#define	AES_CR_FBSEL_Pos                                    (21)
#define	AES_CR_FBSEL                                        (0x0EU << AES_CR_FBSEL_Pos)
