#define	FLASH_CR_PG_Pos                                     (0)
#define	FLASH_CR_PG                                         (0x00U << FLASH_CR_PG_Pos)
#define	FLASH_CR_PER_Pos                                    (1)
#define	FLASH_CR_PER                                        (0x01U << FLASH_CR_PER_Pos)
#define	FLASH_CR_MER_Pos                                    (2)
#define	FLASH_CR_MER                                        (0x02U << FLASH_CR_MER_Pos)
#define	FLASH_CR_OPTPG_Pos                                  (4)
#define	FLASH_CR_OPTPG                                      (0x04U << FLASH_CR_OPTPG_Pos)
#define	FLASH_CR_OPTER_Pos                                  (5)
#define	FLASH_CR_OPTER                                      (0x05U << FLASH_CR_OPTER_Pos)
#define	FLASH_CR_STRT_Pos                                   (6)
#define	FLASH_CR_STRT                                       (0x06U << FLASH_CR_STRT_Pos)
#define	FLASH_CR_LOCK_Pos                                   (7)
#define	FLASH_CR_LOCK                                       (0x07U << FLASH_CR_LOCK_Pos)
#define	FLASH_CR_OPTWRE_Pos                                 (9)
#define	FLASH_CR_OPTWRE                                     (0x09U << FLASH_CR_OPTWRE_Pos)
#define	FLASH_CR_ERRIE_Pos                                  (10)
#define	FLASH_CR_ERRIE                                      (0x0AU << FLASH_CR_ERRIE_Pos)
#define	FLASH_CR_EOPIE_Pos                                  (12)
#define	FLASH_CR_EOPIE                                      (0x0CU << FLASH_CR_EOPIE_Pos)
