#define	FLASH_OBR_OPTERR_Pos                                (0)
#define	FLASH_OBR_OPTERR                                    (0x00U << FLASH_OBR_OPTERR_Pos)
#define	FLASH_OBR_USER_Pos                                  (6)
#define	FLASH_OBR_USER                                      (0x02U << FLASH_OBR_USER_Pos)
#define	FLASH_OBR_Data0_Pos                                 (15)
#define	FLASH_OBR_Data0                                     (0x04U << FLASH_OBR_Data0_Pos)
#define	FLASH_OBR_Data0_Pos                                 (17)
#define	FLASH_OBR_Data0                                     (0x05U << FLASH_OBR_Data0_Pos)
#define	FLASH_OBR_Data1_Pos                                 (25)
#define	FLASH_OBR_Data1                                     (0x06U << FLASH_OBR_Data1_Pos)
