#define	ADC_CFGR_ADEN_Pos                                   (0)
#define	ADC_CFGR_ADEN                                       (0x00U << ADC_CFGR_ADEN_Pos)
#define	ADC_CFGR_ADWEN_Pos                                  (1)
#define	ADC_CFGR_ADWEN                                      (0x01U << ADC_CFGR_ADWEN_Pos)
#define	ADC_CFGR_TVSEN_Pos                                  (2)
#define	ADC_CFGR_TVSEN                                      (0x02U << ADC_CFGR_TVSEN_Pos)
#define	ADC_CFGR_ADCPRE_Pos                                 (6)
#define	ADC_CFGR_ADCPRE                                     (0x04U << ADC_CFGR_ADCPRE_Pos)
#define	ADC_CFGR_RSLTCTL_Pos                                (9)
#define	ADC_CFGR_RSLTCTL                                    (0x05U << ADC_CFGR_RSLTCTL_Pos)
#define	ADC_CFGR_SAMCTL_Pos                                 (12)
#define	ADC_CFGR_SAMCTL                                     (0x06U << ADC_CFGR_SAMCTL_Pos)
