#define	ADC_CR_ADIE_Pos                                     (0)
#define	ADC_CR_ADIE                                         (0x00U << ADC_CR_ADIE_Pos)
#define	ADC_CR_ADWIE_Pos                                    (1)
#define	ADC_CR_ADWIE                                        (0x01U << ADC_CR_ADWIE_Pos)
#define	ADC_CR_TRGEN_Pos                                    (2)
#define	ADC_CR_TRGEN                                        (0x02U << ADC_CR_TRGEN_Pos)
#define	ADC_CR_DMAEN_Pos                                    (3)
#define	ADC_CR_DMAEN                                        (0x03U << ADC_CR_DMAEN_Pos)
#define	ADC_CR_TRGSEL_Pos                                   (6)
#define	ADC_CR_TRGSEL                                       (0x04U << ADC_CR_TRGSEL_Pos)
#define	ADC_CR_SYNCEN_Pos                                   (7)
#define	ADC_CR_SYNCEN                                       (0x05U << ADC_CR_SYNCEN_Pos)
#define	ADC_CR_ADST_Pos                                     (8)
#define	ADC_CR_ADST                                         (0x06U << ADC_CR_ADST_Pos)
#define	ADC_CR_MODE_Pos                                     (10)
#define	ADC_CR_MODE                                         (0x07U << ADC_CR_MODE_Pos)
#define	ADC_CR_ALIGN_Pos                                    (11)
#define	ADC_CR_ALIGN                                        (0x08U << ADC_CR_ALIGN_Pos)
#define	ADC_CR_CMPCH_Pos                                    (15)
#define	ADC_CR_CMPCH                                        (0x09U << ADC_CR_CMPCH_Pos)
