#define	ADC_SR_ADIF_Pos                                     (0)
#define	ADC_SR_ADIF                                         (0x00U << ADC_SR_ADIF_Pos)
#define	ADC_SR_ADWIF_Pos                                    (1)
#define	ADC_SR_ADWIF                                        (0x01U << ADC_SR_ADWIF_Pos)
#define	ADC_SR_BUSY_Pos                                     (2)
#define	ADC_SR_BUSY                                         (0x02U << ADC_SR_BUSY_Pos)
#define	ADC_SR_CH_Pos                                       (7)
#define	ADC_SR_CH                                           (0x04U << ADC_SR_CH_Pos)
#define	ADC_SR_VALID_Pos                                    (16)
#define	ADC_SR_VALID                                        (0x05U << ADC_SR_VALID_Pos)
#define	ADC_SR_OVERRUN_Pos                                  (28)
#define	ADC_SR_OVERRUN                                      (0x07U << ADC_SR_OVERRUN_Pos)
