#define	TIM_CCER_CC1EN_Pos                                  (0)
#define	TIM_CCER_CC1EN                                      (0x00U << TIM_CCER_CC1EN_Pos)
#define	TIM_CCER_CC1P_Pos                                   (1)
#define	TIM_CCER_CC1P                                       (0x01U << TIM_CCER_CC1P_Pos)
#define	TIM_CCER_CC1NEN_Pos                                 (2)
#define	TIM_CCER_CC1NEN                                     (0x02U << TIM_CCER_CC1NEN_Pos)
#define	TIM_CCER_CC1NP_Pos                                  (3)
#define	TIM_CCER_CC1NP                                      (0x03U << TIM_CCER_CC1NP_Pos)
#define	TIM_CCER_CC2EN_Pos                                  (4)
#define	TIM_CCER_CC2EN                                      (0x04U << TIM_CCER_CC2EN_Pos)
#define	TIM_CCER_CC2P_Pos                                   (5)
#define	TIM_CCER_CC2P                                       (0x05U << TIM_CCER_CC2P_Pos)
#define	TIM_CCER_CC2NEN_Pos                                 (6)
#define	TIM_CCER_CC2NEN                                     (0x06U << TIM_CCER_CC2NEN_Pos)
#define	TIM_CCER_CC2NP_Pos                                  (7)
#define	TIM_CCER_CC2NP                                      (0x07U << TIM_CCER_CC2NP_Pos)
#define	TIM_CCER_CC3EN_Pos                                  (8)
#define	TIM_CCER_CC3EN                                      (0x08U << TIM_CCER_CC3EN_Pos)
#define	TIM_CCER_CC3P_Pos                                   (9)
#define	TIM_CCER_CC3P                                       (0x09U << TIM_CCER_CC3P_Pos)
#define	TIM_CCER_CC3NEN_Pos                                 (10)
#define	TIM_CCER_CC3NEN                                     (0x0AU << TIM_CCER_CC3NEN_Pos)
#define	TIM_CCER_CC3NP_Pos                                  (11)
#define	TIM_CCER_CC3NP                                      (0x0BU << TIM_CCER_CC3NP_Pos)
#define	TIM_CCER_CC4EN_Pos                                  (12)
#define	TIM_CCER_CC4EN                                      (0x0CU << TIM_CCER_CC4EN_Pos)
#define	TIM_CCER_CC4P_Pos                                   (13)
#define	TIM_CCER_CC4P                                       (0x0DU << TIM_CCER_CC4P_Pos)
