#define	TIM_CCMR1_CC1S_Pos                                  (1)
#define	TIM_CCMR1_CC1S                                      (0x00U << TIM_CCMR1_CC1S_Pos)
#define	TIM_CCMR1_IC1PSC_Pos                                (3)
#define	TIM_CCMR1_IC1PSC                                    (0x01U << TIM_CCMR1_IC1PSC_Pos)
#define	TIM_CCMR1_IC1F_Pos                                  (7)
#define	TIM_CCMR1_IC1F                                      (0x02U << TIM_CCMR1_IC1F_Pos)
#define	TIM_CCMR1_CC2S_Pos                                  (9)
#define	TIM_CCMR1_CC2S                                      (0x03U << TIM_CCMR1_CC2S_Pos)
#define	TIM_CCMR1_IC2PSC_Pos                                (11)
#define	TIM_CCMR1_IC2PSC                                    (0x04U << TIM_CCMR1_IC2PSC_Pos)
#define	TIM_CCMR1_IC2F_Pos                                  (15)
#define	TIM_CCMR1_IC2F                                      (0x05U << TIM_CCMR1_IC2F_Pos)
#define	TIM_CCMR1_CC1S_Pos                                  (17)
#define	TIM_CCMR1_CC1S                                      (0x06U << TIM_CCMR1_CC1S_Pos)
#define	TIM_CCMR1_OC1FE_Pos                                 (18)
#define	TIM_CCMR1_OC1FE                                     (0x07U << TIM_CCMR1_OC1FE_Pos)
#define	TIM_CCMR1_OC1PE_Pos                                 (19)
#define	TIM_CCMR1_OC1PE                                     (0x08U << TIM_CCMR1_OC1PE_Pos)
#define	TIM_CCMR1_OC1M_Pos                                  (22)
#define	TIM_CCMR1_OC1M                                      (0x09U << TIM_CCMR1_OC1M_Pos)
#define	TIM_CCMR1_OC1CE_Pos                                 (23)
#define	TIM_CCMR1_OC1CE                                     (0x0AU << TIM_CCMR1_OC1CE_Pos)
#define	TIM_CCMR1_CC2S_Pos                                  (25)
#define	TIM_CCMR1_CC2S                                      (0x0BU << TIM_CCMR1_CC2S_Pos)
#define	TIM_CCMR1_OC2FE_Pos                                 (26)
#define	TIM_CCMR1_OC2FE                                     (0x0CU << TIM_CCMR1_OC2FE_Pos)
#define	TIM_CCMR1_OC2PE_Pos                                 (27)
#define	TIM_CCMR1_OC2PE                                     (0x0DU << TIM_CCMR1_OC2PE_Pos)
#define	TIM_CCMR1_OC2M_Pos                                  (30)
#define	TIM_CCMR1_OC2M                                      (0x0EU << TIM_CCMR1_OC2M_Pos)
#define	TIM_CCMR1_OC2CE_Pos                                 (31)
#define	TIM_CCMR1_OC2CE                                     (0x0FU << TIM_CCMR1_OC2CE_Pos)
