#define	TIM_CCMR2_CC3S_Pos                                  (1)
#define	TIM_CCMR2_CC3S                                      (0x00U << TIM_CCMR2_CC3S_Pos)
#define	TIM_CCMR2_IC3PSC_Pos                                (3)
#define	TIM_CCMR2_IC3PSC                                    (0x01U << TIM_CCMR2_IC3PSC_Pos)
#define	TIM_CCMR2_IC3F_Pos                                  (7)
#define	TIM_CCMR2_IC3F                                      (0x02U << TIM_CCMR2_IC3F_Pos)
#define	TIM_CCMR2_CC4S_Pos                                  (9)
#define	TIM_CCMR2_CC4S                                      (0x03U << TIM_CCMR2_CC4S_Pos)
#define	TIM_CCMR2_IC4PSC_Pos                                (11)
#define	TIM_CCMR2_IC4PSC                                    (0x04U << TIM_CCMR2_IC4PSC_Pos)
#define	TIM_CCMR2_IC4F_Pos                                  (15)
#define	TIM_CCMR2_IC4F                                      (0x05U << TIM_CCMR2_IC4F_Pos)
#define	TIM_CCMR2_CC3S_Pos                                  (17)
#define	TIM_CCMR2_CC3S                                      (0x06U << TIM_CCMR2_CC3S_Pos)
#define	TIM_CCMR2_OC3FE_Pos                                 (18)
#define	TIM_CCMR2_OC3FE                                     (0x07U << TIM_CCMR2_OC3FE_Pos)
#define	TIM_CCMR2_OC3PE_Pos                                 (19)
#define	TIM_CCMR2_OC3PE                                     (0x08U << TIM_CCMR2_OC3PE_Pos)
#define	TIM_CCMR2_OC3M_Pos                                  (22)
#define	TIM_CCMR2_OC3M                                      (0x09U << TIM_CCMR2_OC3M_Pos)
#define	TIM_CCMR2_OC3CE_Pos                                 (23)
#define	TIM_CCMR2_OC3CE                                     (0x0AU << TIM_CCMR2_OC3CE_Pos)
#define	TIM_CCMR2_CC4S_Pos                                  (25)
#define	TIM_CCMR2_CC4S                                      (0x0BU << TIM_CCMR2_CC4S_Pos)
#define	TIM_CCMR2_OC4FE_Pos                                 (26)
#define	TIM_CCMR2_OC4FE                                     (0x0CU << TIM_CCMR2_OC4FE_Pos)
#define	TIM_CCMR2_OC4PE_Pos                                 (27)
#define	TIM_CCMR2_OC4PE                                     (0x0DU << TIM_CCMR2_OC4PE_Pos)
#define	TIM_CCMR2_OC4M_Pos                                  (30)
#define	TIM_CCMR2_OC4M                                      (0x0EU << TIM_CCMR2_OC4M_Pos)
#define	TIM_CCMR2_OC4CE_Pos                                 (31)
#define	TIM_CCMR2_OC4CE                                     (0x0FU << TIM_CCMR2_OC4CE_Pos)
