#define	TIM_CR2_CCPC_Pos                                    (0)
#define	TIM_CR2_CCPC                                        (0x00U << TIM_CR2_CCPC_Pos)
#define	TIM_CR2_CCUS_Pos                                    (2)
#define	TIM_CR2_CCUS                                        (0x02U << TIM_CR2_CCUS_Pos)
#define	TIM_CR2_CCDS_Pos                                    (3)
#define	TIM_CR2_CCDS                                        (0x03U << TIM_CR2_CCDS_Pos)
#define	TIM_CR2_MMS_Pos                                     (6)
#define	TIM_CR2_MMS                                         (0x04U << TIM_CR2_MMS_Pos)
#define	TIM_CR2_TI1S_Pos                                    (7)
#define	TIM_CR2_TI1S                                        (0x05U << TIM_CR2_TI1S_Pos)
#define	TIM_CR2_OIS1_Pos                                    (8)
#define	TIM_CR2_OIS1                                        (0x06U << TIM_CR2_OIS1_Pos)
#define	TIM_CR2_OIS1N_Pos                                   (9)
#define	TIM_CR2_OIS1N                                       (0x07U << TIM_CR2_OIS1N_Pos)
#define	TIM_CR2_OIS2_Pos                                    (10)
#define	TIM_CR2_OIS2                                        (0x08U << TIM_CR2_OIS2_Pos)
#define	TIM_CR2_OIS2N_Pos                                   (11)
#define	TIM_CR2_OIS2N                                       (0x09U << TIM_CR2_OIS2N_Pos)
#define	TIM_CR2_OIS3_Pos                                    (12)
#define	TIM_CR2_OIS3                                        (0x0AU << TIM_CR2_OIS3_Pos)
#define	TIM_CR2_OIS3N_Pos                                   (13)
#define	TIM_CR2_OIS3N                                       (0x0BU << TIM_CR2_OIS3N_Pos)
#define	TIM_CR2_OIS4_Pos                                    (14)
#define	TIM_CR2_OIS4                                        (0x0CU << TIM_CR2_OIS4_Pos)
