#define	TIM_EGR_UG_Pos                                      (0)
#define	TIM_EGR_UG                                          (0x00U << TIM_EGR_UG_Pos)
#define	TIM_EGR_CC1G_Pos                                    (1)
#define	TIM_EGR_CC1G                                        (0x01U << TIM_EGR_CC1G_Pos)
#define	TIM_EGR_CC2G_Pos                                    (2)
#define	TIM_EGR_CC2G                                        (0x02U << TIM_EGR_CC2G_Pos)
#define	TIM_EGR_CC3G_Pos                                    (3)
#define	TIM_EGR_CC3G                                        (0x03U << TIM_EGR_CC3G_Pos)
#define	TIM_EGR_CC4G_Pos                                    (4)
#define	TIM_EGR_CC4G                                        (0x04U << TIM_EGR_CC4G_Pos)
#define	TIM_EGR_COMG_Pos                                    (5)
#define	TIM_EGR_COMG                                        (0x05U << TIM_EGR_COMG_Pos)
#define	TIM_EGR_TG_Pos                                      (6)
#define	TIM_EGR_TG                                          (0x06U << TIM_EGR_TG_Pos)
#define	TIM_EGR_BG_Pos                                      (7)
#define	TIM_EGR_BG                                          (0x07U << TIM_EGR_BG_Pos)
