#define	TIM_SR_UI_Pos                                       (0)
#define	TIM_SR_UI                                           (0x00U << TIM_SR_UI_Pos)
#define	TIM_SR_CC1I_Pos                                     (1)
#define	TIM_SR_CC1I                                         (0x01U << TIM_SR_CC1I_Pos)
#define	TIM_SR_CC2I_Pos                                     (2)
#define	TIM_SR_CC2I                                         (0x02U << TIM_SR_CC2I_Pos)
#define	TIM_SR_CC3I_Pos                                     (3)
#define	TIM_SR_CC3I                                         (0x03U << TIM_SR_CC3I_Pos)
#define	TIM_SR_CC4I_Pos                                     (4)
#define	TIM_SR_CC4I                                         (0x04U << TIM_SR_CC4I_Pos)
#define	TIM_SR_COMI_Pos                                     (5)
#define	TIM_SR_COMI                                         (0x05U << TIM_SR_COMI_Pos)
#define	TIM_SR_TI_Pos                                       (6)
#define	TIM_SR_TI                                           (0x06U << TIM_SR_TI_Pos)
#define	TIM_SR_BI_Pos                                       (7)
#define	TIM_SR_BI                                           (0x07U << TIM_SR_BI_Pos)
#define	TIM_SR_CC1O_Pos                                     (9)
#define	TIM_SR_CC1O                                         (0x09U << TIM_SR_CC1O_Pos)
#define	TIM_SR_CC2O_Pos                                     (10)
#define	TIM_SR_CC2O                                         (0x0AU << TIM_SR_CC2O_Pos)
#define	TIM_SR_CC3O_Pos                                     (11)
#define	TIM_SR_CC3O                                         (0x0BU << TIM_SR_CC3O_Pos)
#define	TIM_SR_CC4O_Pos                                     (12)
#define	TIM_SR_CC4O                                         (0x0CU << TIM_SR_CC4O_Pos)
