#define	PWR_CR_PDDS_Pos                                     (1)
#define	PWR_CR_PDDS                                         (0x01U << PWR_CR_PDDS_Pos)
#define	PWR_CR_CWUF_Pos                                     (2)
#define	PWR_CR_CWUF                                         (0x02U << PWR_CR_CWUF_Pos)
#define	PWR_CR_CSBF_Pos                                     (3)
#define	PWR_CR_CSBF                                         (0x03U << PWR_CR_CSBF_Pos)
#define	PWR_CR_PVDE_Pos                                     (4)
#define	PWR_CR_PVDE                                         (0x04U << PWR_CR_PVDE_Pos)
#define	PWR_CR_DBP_Pos                                      (8)
#define	PWR_CR_DBP                                          (0x06U << PWR_CR_DBP_Pos)
#define	PWR_CR_PLS_Pos                                      (12)
#define	PWR_CR_PLS                                          (0x07U << PWR_CR_PLS_Pos)
