#define	DBG_MCU_CR_SLEEP_Pos                                (0)
#define	DBG_MCU_CR_SLEEP                                    (0x00U << DBG_MCU_CR_SLEEP_Pos)
#define	DBG_MCU_CR_STOP_Pos                                 (1)
#define	DBG_MCU_CR_STOP                                     (0x01U << DBG_MCU_CR_STOP_Pos)
#define	DBG_MCU_CR_STANDBY_Pos                              (2)
#define	DBG_MCU_CR_STANDBY                                  (0x02U << DBG_MCU_CR_STANDBY_Pos)
#define	DBG_MCU_CR_IWDG_STOP_Pos                            (8)
#define	DBG_MCU_CR_IWDG_STOP                                (0x04U << DBG_MCU_CR_IWDG_STOP_Pos)
#define	DBG_MCU_CR_WWDG_STOP_Pos                            (9)
#define	DBG_MCU_CR_WWDG_STOP                                (0x05U << DBG_MCU_CR_WWDG_STOP_Pos)
#define	DBG_MCU_CR_TIMx_STOP_Pos                            (13)
#define	DBG_MCU_CR_TIMx_STOP                                (0x06U << DBG_MCU_CR_TIMx_STOP_Pos)
