#define	CAN_BTR1_TESG1_Pos                                  (3)
#define	CAN_BTR1_TESG1                                      (0x00U << CAN_BTR1_TESG1_Pos)
#define	CAN_BTR1_TESG2_Pos                                  (6)
#define	CAN_BTR1_TESG2                                      (0x01U << CAN_BTR1_TESG2_Pos)
#define	CAN_BTR1_SAM_Pos                                    (7)
#define	CAN_BTR1_SAM                                        (0x02U << CAN_BTR1_SAM_Pos)
