#define	CAN_CMR_TR_Pos                                      (0)
#define	CAN_CMR_TR                                          (0x00U << CAN_CMR_TR_Pos)
#define	CAN_CMR_AT_Pos                                      (1)
#define	CAN_CMR_AT                                          (0x01U << CAN_CMR_AT_Pos)
#define	CAN_CMR_RRB_Pos                                     (2)
#define	CAN_CMR_RRB                                         (0x02U << CAN_CMR_RRB_Pos)
#define	CAN_CMR_CDO_Pos                                     (3)
#define	CAN_CMR_CDO                                         (0x03U << CAN_CMR_CDO_Pos)
#define	CAN_CMR_SRR_Pos                                     (4)
#define	CAN_CMR_SRR                                         (0x04U << CAN_CMR_SRR_Pos)
