#define	CAN_CR_RR_Pos                                       (0)
#define	CAN_CR_RR                                           (0x00U << CAN_CR_RR_Pos)
#define	CAN_CR_RIE_Pos                                      (1)
#define	CAN_CR_RIE                                          (0x01U << CAN_CR_RIE_Pos)
#define	CAN_CR_TIE_Pos                                      (2)
#define	CAN_CR_TIE                                          (0x02U << CAN_CR_TIE_Pos)
#define	CAN_CR_EIE_Pos                                      (3)
#define	CAN_CR_EIE                                          (0x03U << CAN_CR_EIE_Pos)
#define	CAN_CR_OIE_Pos                                      (4)
#define	CAN_CR_OIE                                          (0x04U << CAN_CR_OIE_Pos)
