#define	CAN_IER_RIE_Pos                                     (0)
#define	CAN_IER_RIE                                         (0x00U << CAN_IER_RIE_Pos)
#define	CAN_IER_TIE_Pos                                     (1)
#define	CAN_IER_TIE                                         (0x01U << CAN_IER_TIE_Pos)
#define	CAN_IER_EIE_Pos                                     (2)
#define	CAN_IER_EIE                                         (0x02U << CAN_IER_EIE_Pos)
#define	CAN_IER_DOIE_Pos                                    (3)
#define	CAN_IER_DOIE                                        (0x03U << CAN_IER_DOIE_Pos)
#define	CAN_IER_EPIE_Pos                                    (5)
#define	CAN_IER_EPIE                                        (0x05U << CAN_IER_EPIE_Pos)
#define	CAN_IER_ALIE_Pos                                    (6)
#define	CAN_IER_ALIE                                        (0x06U << CAN_IER_ALIE_Pos)
#define	CAN_IER_BEIE_Pos                                    (7)
#define	CAN_IER_BEIE                                        (0x07U << CAN_IER_BEIE_Pos)
