#define	CAN_IR_RI_Pos                                       (0)
#define	CAN_IR_RI                                           (0x00U << CAN_IR_RI_Pos)
#define	CAN_IR_TI_Pos                                       (1)
#define	CAN_IR_TI                                           (0x01U << CAN_IR_TI_Pos)
#define	CAN_IR_EI_Pos                                       (2)
#define	CAN_IR_EI                                           (0x02U << CAN_IR_EI_Pos)
#define	CAN_IR_DOI_Pos                                      (3)
#define	CAN_IR_DOI                                          (0x03U << CAN_IR_DOI_Pos)
#define	CAN_IR_EPI_Pos                                      (5)
#define	CAN_IR_EPI                                          (0x05U << CAN_IR_EPI_Pos)
#define	CAN_IR_ALI_Pos                                      (6)
#define	CAN_IR_ALI                                          (0x06U << CAN_IR_ALI_Pos)
#define	CAN_IR_BEI_Pos                                      (7)
#define	CAN_IR_BEI                                          (0x07U << CAN_IR_BEI_Pos)
