#define	CAN_MOD_RM_Pos                                      (0)
#define	CAN_MOD_RM                                          (0x00U << CAN_MOD_RM_Pos)
#define	CAN_MOD_LOM_Pos                                     (1)
#define	CAN_MOD_LOM                                         (0x01U << CAN_MOD_LOM_Pos)
#define	CAN_MOD_STM_Pos                                     (2)
#define	CAN_MOD_STM                                         (0x02U << CAN_MOD_STM_Pos)
#define	CAN_MOD_AFM_Pos                                     (3)
#define	CAN_MOD_AFM                                         (0x03U << CAN_MOD_AFM_Pos)
