#define	CAN_SR_RBS_Pos                                      (0)
#define	CAN_SR_RBS                                          (0x00U << CAN_SR_RBS_Pos)
#define	CAN_SR_DOS_Pos                                      (1)
#define	CAN_SR_DOS                                          (0x01U << CAN_SR_DOS_Pos)
#define	CAN_SR_TBS_Pos                                      (2)
#define	CAN_SR_TBS                                          (0x02U << CAN_SR_TBS_Pos)
#define	CAN_SR_TCS_Pos                                      (3)
#define	CAN_SR_TCS                                          (0x03U << CAN_SR_TCS_Pos)
#define	CAN_SR_RS_Pos                                       (4)
#define	CAN_SR_RS                                           (0x04U << CAN_SR_RS_Pos)
#define	CAN_SR_TS_Pos                                       (5)
#define	CAN_SR_TS                                           (0x05U << CAN_SR_TS_Pos)
#define	CAN_SR_ES_Pos                                       (6)
#define	CAN_SR_ES                                           (0x06U << CAN_SR_ES_Pos)
#define	CAN_SR_BS_Pos                                       (7)
#define	CAN_SR_BS                                           (0x07U << CAN_SR_BS_Pos)
