#define	RTC_CSR_SECF_Pos                                    (0)
#define	RTC_CSR_SECF                                        (0x00U << RTC_CSR_SECF_Pos)
#define	RTC_CSR_ALRF_Pos                                    (1)
#define	RTC_CSR_ALRF                                        (0x01U << RTC_CSR_ALRF_Pos)
#define	RTC_CSR_OWF_Pos                                     (2)
#define	RTC_CSR_OWF                                         (0x02U << RTC_CSR_OWF_Pos)
#define	RTC_CSR_RSF_Pos                                     (3)
#define	RTC_CSR_RSF                                         (0x03U << RTC_CSR_RSF_Pos)
#define	RTC_CSR_CNF_Pos                                     (4)
#define	RTC_CSR_CNF                                         (0x04U << RTC_CSR_CNF_Pos)
#define	RTC_CSR_RTOFF_Pos                                   (5)
#define	RTC_CSR_RTOFF                                       (0x05U << RTC_CSR_RTOFF_Pos)
